### ISSUE TITLE
Tunslip on Raspberry PI

### ISSUE THREAD

**Issue by latapata** [contiki-os/contiki#1006]
Hello All,

I want to connect CC2358dk RPL border router to Raspberry Pi via UART. Inside Raspberry PI I want to run tunslip6 utility. 

I just want to replace the instant-contiki with a Raspbian.

 Is this possible ?

**Comment by dmazzer** [comment]
Hi,

I have run tunslip6 on a BeagleBone without any problem.
You will need to enable network tunneling protocols in kernel.

Regards,

_______________ _____ _____ __ ___ __ _ _ _  _
Daniel Mazzer
dmazzer@gmail.com
skype: danielmazzer

**Comment by latapata** [comment]
I did not use Raspeberry Pi instead I started using a live Ubuntu booted from USB and running the tunslip on a computer to connect my border router.

Thanks for your answer @dmazzer
