### ISSUE TITLE
cc2538 is not detecting as ttyUSB

### ISSUE THREAD

**Issue by Devesh24** [contiki-os/contiki#1043]
Hello Guys,
                   I am trying to rpl-border-router by putting RF board on EM , but when i am doing 
"ls /dev | grep ttyUSB" its not been detected , while i am using RF board directly is been detected as ttyACMx.
I have done the following changes in "platform/cc2538dk/contiki-conf.h"
#define UART_CONF_ENABLE            0
#define SLIP_ARCH_CONF_USB          1
#define DBG_CONF_USB                1 
lsusb output is showing the device  
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 024: ID 0403:a6d1 Future Technology Devices International, Ltd 
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

Toochain is 
gcc version 4.9.3 20150303 (release) [ARM/embedded-4_9-branch revision 221220] (GNU Tools for ARM Embedded Processors) 
Thanks

**Comment by g-oikonomou** [comment]
it is very unclear what your problem is. Irrespectively, I just tried CC2538 border routers over UART as well as over USB and they are working perfectly.
