### ISSUE TITLE
Debug Contiki

### ISSUE THREAD

**Issue by mistergomes** [contiki-os/contiki#1079]
Hey guys,

Sorry if this question doesn't fit here but,:
I have been using Contiki 2.7 under Eclipse IDE (Windows platform) for developing some applications and run the included examples.
My dev platform is the CC2538DK from Texas Instruments. I have the SmartRF06 boards as well some customized dev boards that I did by myself.
How do you guys debug your applications? I'm trying to use an external debugger and the debugger that comes with the kit, but still... I cant go into the application debug, just the contiki-main.c
If I try to "run" the code, the system gets stuck on the

void default_handler(void) {while(1);}

Do you guys suggest anything "better" to debug?

Cheers,
TG

**Comment by vsaw** [comment]
Two things

1. Some interrupt seems to be firing that is not handled. Try checking all the interrupt flags on your system to see what is going on. You should also be able to check the stack trace to see where program execution has been interrupted.
2. These kinds of things are usually discussed on the contiki mailing list. GitHub is supposed to be used for Contiki Development Only. See the [wiki](https://github.com/contiki-os/contiki/wiki#Help) for more help

:-)
