### ISSUE TITLE
CC26xx ADC Support in ti-lib.h

### ISSUE THREAD

**Issue by tonnenpinguin** [contiki-os/contiki#1087]
Hi guys,

My apologies if this has been discussed before, but I could not find it anywhere.

The cc26xxware driver lib includes a file called aux_adc.h, however these functions are not included in the ti-lib.h

Has anybody included that yet, or is there a specific reason why it is not included in the ti-lib.h?

Thanks!

**Comment by g-oikonomou** [comment]
No technical reason as such, just that the port doesn't use this particular CC26xxware functionality.
