### ISSUE TITLE
Cooja simulator giving errors:  "TSCH-queue:! add packet failed"

### ISSUE THREAD

**Issue by sdartue** [contiki-os/contiki#1130]
When I run a cooja simulation for 3 minutes or more then I keep getting these errors.
TSCH-queue:! add packet failed: 0 0x236a 3 0 0
TSCH:! can't send packet !tsch_queue_add_packet

Initially everythin is ok but after sometime this error starts. I keep getting this error and I dont see any data transfer. Can someone please help me with this?

**Comment by g-oikonomou** [comment]
Contiki doesn't support TSCH, (not to my knowledge anyway!). Thus, I'm closing this as invalid.
