### ISSUE TITLE
CC2650 does not work even printf

### ISSUE THREAD

**Issue by vk8051** [contiki-os/contiki#1176]
Hi,
I compiled the contiki0master/example/cc26xx and I upload the cc26xx-demo.bin.
The chip does not work even prinf

**Comment by g-oikonomou** [comment]
Judging by your posts to the mailing list, I am assuming that you have resolved this. Closing

**Comment by kainataltaf** [comment]
@vk8051 
How did you solve this issue? I am facing the same.

**Comment by vk8051** [comment]
> @vk8051
> How did you solve this issue? I am facing the same.

Hi Kainataltaf,
Would you take a look this link.
https://e2e.ti.com/support/legacy_forums/embedded/tirtos/f/355/p/544801/1987456

I don't use cc2650 chip so long.
I suggest you go to TI website:
 https://e2e.ti.com/
There are many people ask question here.

Vincent
