### ISSUE TITLE
coap server not building for sky

### ISSUE THREAD

**Issue by lovelesh** [contiki-os/contiki#1210]
Hi,

I tried to build the er-example-server for sky but there are memory overflow issues. The ROM gets overflow error. Rest other files like er-example-client.c er-example-observe-client.c builds fine. All the files builds nicely in release 2.7 branch.

**Comment by alignan** [comment]
The stack has grown since 2.7, alternatively you could disable some of the resources and save space.

See:

http://stackoverflow.com/questions/35894400/cannot-fit-er-example-server-to-telosb/36156708#36156708
