### ISSUE TITLE
Update to newest cc26xxware release

### ISSUE THREAD

**Issue by tonnenpinguin** [contiki-os/contiki#1211]
Hi guys,

I've just stumbled upon the [newest release](http://processors.wiki.ti.com/index.php/CC26xxWare#Release_notes_v2.21.03.15980) of cc26xxware and wondered if  @g-oikonomou could please update the submodule when he's free!

Alternatively, I can prepare a pull request, too!

All the best,
tonnenpinguin

**Comment by g-oikonomou** [comment]
There's a PR due to appear over the next few days, so I'd advise against spending any effort on this.

**Comment by tonnenpinguin** [comment]
Alright, thank you!
