### ISSUE TITLE
CC2650STK Very Sleepy Demo

### ISSUE THREAD

**Issue by chenek** [contiki-os/contiki#1221]
I pull latest Contiki from github and build Very Sleepy Demo for CC2650STK. After I download and run it on my CC2650STK. I see the Contiki version is Contiki-2.6-2461-g7dc8ace from UART output like the followings:

Starting Contiki-2.6-2461-g7dc8ace
With DriverLib v0.44336
TI CC2650 SensorTag
Net: sicslowpan
MAC: CSMA
RDC: ContikiMAC, Channel Check Interval: 16 ticks
RF: Channel 25
Very Sleepy Demo Process

However, I see the latest Contiki version should be 3.0. What am I doing wrong?

**Comment by laurentderu** [comment]
You are doing nothing wrong, the version tag is not correctly selected, see #939.
