### ISSUE TITLE
Wrong version in CONTIKI_VERSION_STRING

### ISSUE THREAD

**Issue by arurke** [contiki-os/contiki#1232]
Hi , there seems to be a bug in Makefile.include which updates CONTIKI_VERSION_STRING with the output from "git --git-dir ${CONTIKI}/.git describe --tags --always}". - this cmd returns "2.6-2491-g0fe6256"​. Correct as of now should be 3.0-etc.

The relevant commit is 192d87fa4843745e96499142f4574e696c59bb0a
I'm not a git wizard but maybe committer @cmorty sees a simple fix?

Regards,
Andreas U.

**Comment by alignan** [comment]
It is already addressed here: https://github.com/contiki-os/contiki/issues/939
