### ISSUE TITLE
Energest with NullRDC shows 0% radio duty cycle

### ISSUE THREAD

**Issue by atiselsts** [contiki-os/contiki#1241]
When using energest with NullRDC, on most platforms it will show wrong results (0%) for the radio duty cycle, as energest is initialized after the network stack.

`energest_init()` should be moved before initialization of network's stack, and in fact as high as possible, immediately after `rtimer_init()`, as the same problem may apply to tracking energy usage of other components.

This has been fixed for Sky in #810 by @cmorty, why not do the same for other platforms?

**Comment by cmorty** [comment]
@atiselsts Well, it should be fixed for the other platforms, too. I just happen to work with sky. Maybe it would be a good Idea to move some of this stuff from the platform-specific initialisation sequence to a system-wide initialisation sequence that calls platform-specific functions. That quite a bit of work, though.
