### ISSUE TITLE
ESP8266 Support

### ISSUE THREAD

**Issue by kteza1** [contiki-os/contiki#1248]
Hi. I just found contiki. I couldn't find any esp8266 support. Do you have any plans to support esp8266?

**Comment by chenek** [comment]
Basically, Contiki 6LowPAN is based on 802.15.4 not 802.11. So, I don't think it might be in Contiki Roadmap. I also find this paper (https://www.kth.se/social/upload/53ec9b3ef276544fabdef3e0/glaropoulos_icess2014_submission_64.pdf) which implement 802.11 for Contiki on AR9170.
