### ISSUE TITLE
How to change TX power for CC2650/CC1350?

### ISSUE THREAD

**Issue by chenek** [contiki-os/contiki#1259]
Is there anywhere show us how to change TX power for CC2650/CC1350?

**Comment by tonnenpinguin** [comment]
As far as I know there is no way to do this in contiki currently.

However, there has been a pull request suggesting to add this functionality that has not been merged yet. Have a look at #1189 and #1190.

**Comment by bkozak-scanimetrics** [comment]
I just had a quick look at the driver and it looks like you can set the tx power by calling ```NETSTACK_RADIO.set_value(RADIO_PARAM_TXPOWER,<power in dbm>)``` at some point after the radio is initialized, but I haven't tried it out.
