### ISSUE TITLE
CC26xx / CC13xx - redundant and or wrong PDSTATN checking in rf-core

### ISSUE THREAD

**Issue by bkozak-scanimetrics** [contiki-os/contiki#1279]
I've just had a look at ```rf_core_is_accessible``` in rf-core.c and I think there are some problems with the function.

If we look at the implementation for ```ti_lib_prcm_rf_ready``` and ```ti_lib_prcm_power_domain_status``` we can see that they both check the same bits (note that ```PDSTAT1RFC.ON``` "is an alias" for ```PDCTL1.RFC_ON``` according to the TRM). Also, ```ti_lib_prcm_power_domain_status``` will return a positive result if ```PDCTL0.RFC_ON``` **or** ```PDCTL1.RFC_ON``` are set.

I'm not sure if the ```PDCTL0.RFC_ON || PDCTL1.RFC_ON``` is sufficient; maybe there is some reason that this works but I can't see how. Regardless, there's a redundant read here.

Also , ```rf_core_power_up``` will call ```ti_lib_prcm_power_domain_status``` directly but will then again call it indirectly through ```rf_core_is_accessible``` soon after. This also seems to be redundant (and indeed I've never seen the ```PRINTF("rf_core_power_up: Not ready\n");``` get executed) .

**Comment by g-oikonomou** [comment]
The difference between `PDSTAT0.RFC_ON` and `PDSTAT1.RFC_ON` is unclear to me by reading the TRM. It may have to do with clocks. It appears that `ti_lib_prcm_rf_ready` is more strict. What if e.g. the bit in `PDSTAT0` is set bu the one in `PDSTAT1` is not? The power domain will be reported as on, but perhaps the core won't be "accessible" if you know what I mean.

Good points both of them. I'm running some tests
