### ISSUE TITLE
CC26xx & CC13xx ISR Flag Clear Issue

### ISSUE THREAD

**Issue by bkozak-scanimetrics** [contiki-os/contiki#1294]
In the radio driver ISR routines, the flag register is getting cleared as follows: ```HWREG(RFC_DBELL_NONBUF_BASE + RFC_DBELL_O_RFCPEIFG) = 0x0 ``` 

This is a problem because there are multiple flags which can trigger these routines. We could end up missing an event unnecessarily if the following were to occur:

1. Event A triggers an interrupt
2. The ISR runs, the flag register is read and event A is processed
3. Just before clearing the flag register event B occurs
4. the flag register is cleared and the event B flag is lost

**Comment by g-oikonomou** [comment]
I'm flagging this as a bug. We should clear the corresponding flag within each if block.
