### ISSUE TITLE
power consumption of TI sensortag 2650 demo

### ISSUE THREAD

**Issue by xianlin** [contiki-os/contiki#1305]
#### CC26xx-demo
Source Code is at https://github.com/contiki-os/contiki/blob/master/examples/cc26xx/cc26xx-demo.c

This demo will read sensor reading and print values on the console, blink LED and advertise the BLE.

Supply sensortag with DC 2.7V (not coin cell battery), max current is 3mA and min current is 0.64mA.

When the GREEN LED ON, high current of 3mA, it last for 20 seconds ([as led toggle function starts to run](https://github.com/contiki-os/contiki/blob/master/examples/cc26xx/cc26xx-demo.c#L384))

![cc26xx-demo-high-current-01](https://cloud.githubusercontent.com/assets/1726373/10450722/c2da6346-71ce-11e5-98b8-955ca7382d57.jpg)

When the GREEN LED OFF, low current of 0.64mA (sometimes 0.8mA), now sensortag stops LED toggle, it also last for 20 seconds.

![cc26xx-demo-low-current-02](https://cloud.githubusercontent.com/assets/1726373/10450725/c5cb2702-71ce-11e5-9ceb-0404ccb5017a.jpg)

So if a coin cell battery of 220mAh, with duty cycle of 50% of 3mA and 0.7mA, it can last for about 5 days.

I will carry out next few tests soon. (e.g. 802.15.4 power consumption OR make the update/reading interval longer than 20 seconds, say 5 minutes). 

I will update the power measurement result here. Hopefully we can improve the power consumption and make the code running on the TI sensortag really **lean** and really low power.

**Comment by cmorty** [comment]
You should also get hold of a scope. That might also give you some hints what to look for. Multimeters are only good for estimations. They are often inaccurate when the voltage/current changes a lot.

**Comment by xianlin** [comment]
@cmorty I will try the scope next time. Thanks.

**Comment by adamdunkels** [comment]
@jonnteolsson @g-oikonomou: there seems to be a lot of people seeing these problems, would be great if you guys could look into this given that the Sensortag platform is now one of the primary Contiki platforms.

**Comment by bkozak-scanimetrics** [comment]
My PR #1257 should reduce the 0.64mA current significantly. On my CC26xx evaluation module I get a 40uA reduction in dee-sleep power consumption of the MCU.

**Comment by g-oikonomou** [comment]
Bunch of things going on over the last few weeks, but this is in the ToDo!

**Comment by jonnteolsson** [comment]
@adamdunkels we (@jonnteolsson and @g-oikonomou) will look into this issue starting Monday!

**Comment by bkozak-scanimetrics** [comment]
@jonnteolsson and @g-oikonomou 

I've done some debugging of this myself and have found another problem which is causing high power consumption.

In lpm.c, you do not set an RTC wakeup if no etimer is running which means that we will wake on the next 128Hz clock interval. Ironically, we get higher power consumption if no etimer is running at all than if some etimer is scheduled.

**Comment by xianlin** [comment]
I have conducted a **BLE firmware** power consumption experiment. 

The BLE firmware version is **1.20 (Jul 28 2015)** and the current is fluctuate between **0.5mA to 0.8mA** when idle/not connecting with master device and peak current with **3mA** when connecting with the master device.

The Firmware version:
![firmware](https://cloud.githubusercontent.com/assets/1726373/10597819/63d06aa6-7725-11e5-9ffb-f088e194bc4c.png)


Before connect, just powered on the BLE sensortag 2.0. (advertising interval 100ms and flash LED every 1 second)

![not_connected](https://cloud.githubusercontent.com/assets/1726373/10597827/7b967978-7725-11e5-9000-78fa32fab61a.jpg)

Connecting by using mobile phone app via BLE scanning. (peak current last for about 2 or 3 seconds)

![connecting](https://cloud.githubusercontent.com/assets/1726373/10597830/89ccc8f8-7725-11e5-83ba-87c9780ec5a6.jpg)

After BLE connection established and the andriod mobile app read the sensor value almost every 1000ms. (flutuate between 0.5mA and 0.8mA)

![after_connect](https://cloud.githubusercontent.com/assets/1726373/10597837/8dc62eea-7725-11e5-9e74-bfc2c2bcc58d.jpg)

**Comment by xianlin** [comment]
The below are the result of "**Very Sleepy Demo**" Power measurement by using a multi-meter.

https://github.com/contiki-os/contiki/tree/master/examples/cc26xx/very-sleepy-demo


When the `Mode=0`, sleepy mode is disabled, the current is high at around **2.84mA**

![20151020_161252](https://cloud.githubusercontent.com/assets/1726373/10601923/b3367dac-7747-11e5-8b3e-6d3351085fa0.jpg)

From COAP resource web page you can see the sleepy mode is disabled

![very_sleepy_config](https://cloud.githubusercontent.com/assets/1726373/10601925/b339a8b0-7747-11e5-9fa9-92647f5b5c36.png)

Now enable the sleepy mode by issue a `POST` method to the COAP with message of `mode=1&interval=60&duration=20`

![very_sleepy_config_enabled](https://cloud.githubusercontent.com/assets/1726373/10601926/b3588d70-7747-11e5-8f78-2ff899235cda.png)


So the sensortag will sleep for 40s and wake up for another 20s, total 60s every time. 

The current consumption is at around **0.26mA**

![20151020_161759](https://cloud.githubusercontent.com/assets/1726373/10601924/b33892a4-7747-11e5-81b1-27e6f8cdcff6.jpg)

So if we use duty ratio of **20s/40s every 1 minute**, the 240mAH CR2032 battery can last about **9 days**.

```
(0.26*40 + 2.8*20)/60 = 1.106667 mA
240/1.106667/24 = 9 days
```

if use **20s/100s every 120 seconds(2 minutes)**, it will last about 351 days which is almost **1 year**. (to be verified)

**Comment by xianlin** [comment]
@bkozak-scanimetrics , your post at https://e2e.ti.com/support/wireless_connectivity/f/158/t/452029 mentioned there is a way to reduce the **deep sleep** current to about **1.5uA**.

Is your pull request https://github.com/contiki-os/contiki/pull/1257 being merged already? If it is merged, can it reduced the "Very Sleepy Demo" power consumption to 1.5uA when it is in deep sleep mode?

**Comment by bkozak-scanimetrics** [comment]
@xianlin #1257 does implement the fix I mentioned on the TI forum. I don't know if anyone is considering merging it. Perhaps @g-oikonomou or @jonnteolsson has a better solution in mind for this problem.

I haven't been testing with the Very Sleepy Demo but I believe that #1257 must reduce the deep sleep consumption of the Very Sleepy Demo. As far as I know, there could be some other issue with that example which prevents sleeping at 1.5uA.

**Comment by g-oikonomou** [comment]
Yes, #1257 is being considered. So is input in this thread here, other open related issues as well as various discussions in the mailing list. Thanks for the input, your patience is appreciated! :)

**Comment by xianlin** [comment]
I have done the **cc26xx-web-demo** power measurement although using an oscilloscope is accurate but I used a multi-meter for simplicity.

Source Code

https://github.com/contiki-os/contiki/tree/master/examples/cc26xx/cc26xx-web-demo

Note

 - Disabled `net-uart` and `ble` function in the code

When LED is not blinking (`MQTT - Got TCP_DATA_SENT` in the debug output console), the current is below **0.47mA**. 

Here sensortag is **NOT** publishing mqtt messages.

![mqtt_ack](https://cloud.githubusercontent.com/assets/1726373/10626611/6362dc2a-77e3-11e5-94b6-8ae57a7d513a.jpg)


When sensortag starts to publish MQTT message (`MQTT - Sending publish message! topic iot-2/evt/status/fmt/json topic_length 25` in the debug output console), the current is around **3mA** for 2 to 3 seconds) and LED blinks very shortly.

Then it goes back to around **0.47mA** and waits for another publish period.

![mqtt_publish](https://cloud.githubusercontent.com/assets/1726373/10626612/65f7ff24-77e3-11e5-85b2-3776f128c863.jpg)

If I turned off `wrapsix` NAT64 program running on the Boarder Router, the current shoot up to **8mA** while LED keeps on.

![without_nat64_mqtt](https://cloud.githubusercontent.com/assets/1726373/10626618/71c0e3ca-77e3-11e5-91ec-1508375fec8d.jpg)

if I turned off `6lbr` program on Boarder Router, the current stays around **1.7mA** and LED keeps blinking.

![without_6lbr_mqtt](https://cloud.githubusercontent.com/assets/1726373/10626615/6ca7fe64-77e3-11e5-84b8-f14e2360dcd2.jpg)

### Conclusion

If `cc26xx-web-demo` is functioning properly (can publish MQTT message and display sensor reading on the IBM web dashboard) the current consumption is about **3mA** when publishing and **0.47mA** when NOT publishing.

To make this example/demo useful in the real world project, it should utilize **sleepy mode** to extend the battery life.

If the project is DC powered in some cases, it should avoid unnecessary radio messages OR reduce MQTT message length to get more bandwidth for other sensortags in the same network.

**Comment by xianlin** [comment]
@bkozak-scanimetrics ,  I have done the `very-sleepy-demo` by using your PR #1257. 

The current reduced to **0.017mA = 17uA** compared to **0.26mA** with the previous experiment.

![turn_off_radio](https://cloud.githubusercontent.com/assets/1726373/10626889/1eef3a36-77e6-11e5-9898-6e42842854c3.jpg)

Thank you and it is impressive to get **1/15** deduction of the current.

Let's wait for the merge to happen and I will close this issue when it is merged.

**Comment by g-oikonomou** [comment]
#1257 and a number of more recent pulls should be enough to close this one.

**Comment by vicgordienko** [comment]
@xianlin 

> So if we use duty ratio of 20s/40s every 1 minute, the 240mAH CR2032 battery can last about 9 days.
> 
> (0.26*40 + 2.8*20)/60 = 1.106667 mA
> 240/1.106667/24 = 9 days
> if use 20s/100s every 120 seconds(2 minutes), it will last about 351 days which is almost 1 year. (to be verified)

How did you calculate 351 days?
For my  calculation I get:
(0.26*100 + 2.8*20)/120 = 0.683333333 mA
240/240/0.683333333/24 = 9 days/24 = 14.63 days

**Comment by xianlin** [comment]
@vicgordienko you are correct, it should be 14.63 days

**Comment by Ashokrlz** [comment]
Hello everyone,

I'm searching for any documentation of Contiki talking about power consumption of wireless sensor nodes especially for CPU CC2650/CC1350? Regards,
