### ISSUE TITLE
Cooja: How to modify cooja nodes features?

### ISSUE THREAD

**Issue by corralin** [contiki-os/contiki#1325]
Hi!

I have to implement a WSN and based on wake-up radios and measure power consumption.
But i have my own physical nodes, with my own HW which is different from the nodes that are avaible in Cooja. I would like to modify the key features of one of theese nodes, for example, the Sky Mote, in order to implement my parameters.
I use IEEE 802.15.4 by Zigbee (ETRX2), an ADuc841 microcontroller (62kB Flash Memory, 2kB RAM) and also a FPGA Xilinx Spartan 3 XC3S200.
Is there any way to simulate the characteristics of my node and implements them in Cooja?
Maybe creating my own Cooja node or modifying one.

Thanks!

**Comment by alignan** [comment]
Please forward your questions to Contiki mail list
