### ISSUE TITLE
how to run new version of uIP without Contiki?

### ISSUE THREAD

**Issue by myrfy001** [contiki-os/contiki#1326]
hello
the last standalone version of uIP was released in 2013, and the new version is now part of Contiki, so the uIP now seems to rely on some functions provided by Contiki, like process_xxx functions in tcpip.c

so, is there a easy way to run uIP without Contiki?

**Comment by alignan** [comment]
Not precisely a Contiki issue or question, but the sources are available at:

https://github.com/adamdunkels/uip

**Comment by myrfy001** [comment]
@alignan I know standalone uIP code could be found at the url your give me, but the version on that url hasn't been updated since 2013, so, is there any improve for uIP? I think there are some improvements since 2013.
