### ISSUE TITLE
Cooja Error 

### ISSUE THREAD

**Issue by vishal623** [contiki-os/contiki#1328]
Hello,
I get this error when I run the Nomadic mobility model in Cooja. I use rpl-collect example for create sink and sender. Then apply my nomadic movement file to my simulation. After 10:00:000 it give me this error.

java.lang.RuntimeException: Next event is in the past: 124522487 < 606641503: Mobility$2@18db030
[java] at se.sics.cooja.Simulation.run(Simulation.java:276)
[java] at java.lang.Thread.run(Thread.java:745)

This error because of simulation time or other? I generate nomadic movements for 600 sec using bonnmotion.

Please help me.

Vishal

**Comment by cmorty** [comment]
I remember triggering this using RealSim, too. I remember, that I wasn't able to find out why that happened, yet I worked around it. This seems however to be a problem with bonmotion.
