### ISSUE TITLE
cc2650 set TX power

### ISSUE THREAD

**Issue by schuschu** [contiki-os/contiki#1340]
There seems to be an issue with the set_tx_power function. By default, the transmission power in IEEE mode is output_power[0], which corresponds to +5 dBm. At a distance of 10cm, a CC2531 USB dongle receives packets with an RSSI of -39 dBm, which seems reasonable.

However, whenever the NETSTACK_RADIO.set_value(RADIO_PARAM_TXPOWER, ...) function is called (including when the transmission power is set again to +5 dBm), all packets seem to be sent with the lowest transmission power. I indeed receive an RSSI of -76 dBm with the same settings.

Interestingly, the transmission power seems only to change correctly when I change the default value of output_config_t *tx_power_current = &output_power[X].

**Comment by g-oikonomou** [comment]
@schuschu Thanks for this report. Should be fixed with #1350
