### ISSUE TITLE
should off_t type be signed or unsigned? In MSP430 Z1 Platform

### ISSUE THREAD

**Issue by myrfy001** [contiki-os/contiki#1367]
When I using MSP430-GCC, which is the new complier published by TI as the successor of the community driven MSPGCC, I meet the question bellow:

```C
#include "contiki.h"
#include <stdio.h>
```

in contiki.h, it includes the platform-conf.h and it deffines off_t as unsigned long.
in stdio.h, it includes types.h given by Texas Instruments and it defines off_t as long.

Besides Texas Instruments, Linux also defines off_t as long. __So, should the off_t be changed to signed long instead of unsigned long?__

**Comment by cmorty** [comment]
If I understand things right, according to POSIX it should be signed: http://pubs.opengroup.org/onlinepubs/7908799/xsh/systypes.h.html

**Comment by myrfy001** [comment]
So, the problems comes...
When compiling contiki with some other code using POSIX, there will be a type conflict.
Will change contiki's off_t to signed have any bad effects?

**Comment by cmorty** [comment]
My guts tell me it shouldn't have a negative effect. So I suggest to change it, make a pull-request, and see what happens. After all the regression testing is quite comprehensive. Also PRs normally get more attention than issues.

**Comment by g-oikonomou** [comment]
My 2c: if a type is defined in toolchain headers, we shouldn't overwrite said define unless there is a really really really good reason to do so. Even more so if standards have an explicit opinion.

**Comment by alignan** [comment]
@g-oikonomou agree.  Does this break anything? can you `grep` any potential bug?

**Comment by alignan** [comment]
Closing, if you want to create a PR to address the change we can review later.

**Comment by simonduq** [comment]
I agree this type is supposed to signed, and btw the PR is already merged :) https://github.com/contiki-os/contiki/pull/1375

**Comment by alignan** [comment]
Oh nice!
