### ISSUE TITLE
Cooja Simulation mote for Sensortag 2.0 CC2650

### ISSUE THREAD

**Issue by weijian19391** [contiki-os/contiki#1374]
Hi 

May i know if the simulation support for TI Sensortag 2.0 is/will be present in the near future?

**Comment by g-oikonomou** [comment]
Your best bet is emul8:
http://www.rte.se/en/emul8
http://thread.gmane.org/gmane.os.contiki.devel/26059

I don't think the Sensortag will be supported as such (in terms of peripherals), but emul8 is - to my knowledge - the most promising effort to get CM3 support in Cooja.

This discussion is more suitable for the mailing list, so I'm closing this.
