### ISSUE TITLE
payload format not fixed

### ISSUE THREAD

**Issue by bbhagasra1** [contiki-os/contiki#1384]
fix payload data format ...........it is HEX or ASCII ??

**Comment by msloth** [comment]
It's neither and both. It's just data, binary data. Hex and ASCII are just ways to represent the data. Ie, ASCII 'A' is hex 0x41 is decimal 65 is binary 1000001.

Google eg `data representation`.

**Comment by bbhagasra1** [comment]
Hi,
       If input to node(serial port UART) is HEX and node sending over 
the air ASCII then need to covert hex to ascii because receiver node 
understand ASCII at RF channel and again change to ASCII to HEX for 
interface Device(HEX CMD input).

for example :- 0x00 in HEX have value 0 if at RF node(ASCII data format 
used) then value is NULL.

so we need to define input (UART) and RF channel data format same.



On 11/20/2015 7:03 PM, Marcus Linderoth wrote:
>
> It's neither and both. It's just data, binary data. Hex and ASCII are 
> just ways to represent the data. Ie, ASCII 'A' is hex 0x41 is decimal 
> 65 is binary 1000001.
>
> Google eg |data representation|.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/contiki-os/contiki/issues/1384#issuecomment-158404316>.
>

-- 
Thanks
Bijendra Bhagasra


Email Confidentiality Notice and Disclaimer
This email message contains information which may be confidential and or legally privileged. Unless you are the intended recipient (or have been authorized to receive on behalf of the intended recipient), you may not use, copy or disclose to anyone the message or any information contained in the message or from any attachments that were sent with this email. If you have received this email message in error, please advise the sender by email, and delete the message. Further, this message contains views and comments of the individual sending the message and the company is in no way liable for any issues arising from use from such a message.

----------------------------------------------
Genus Power Infrastructures Ltd, Jaipur, India
