### ISSUE TITLE
CC1310DK keep rebooting runing cc26xx-demo with latest Contiki version.

### ISSUE THREAD

**Issue by chenek** [contiki-os/contiki#1465]
Just sync to latest Contiki version and build cc26xx-demo for CC1310DK with "make TARGET=srf06-cc26xx BOARD=srf06/cc13xx cc26xx-demo.bin". The binary will make my CC1310 keep rebooting.

**Comment by chenek** [comment]
arend had find the cause of this problem (https://e2e.ti.com/support/wireless_connectivity/zigbee_6lowpan_802-15-4_mac/f/158/t/482914#pi239031350=2) and need someone to verify this. 

found in "Merge pull request #1350 from g-oikonomou/bugfix/cc26xx/tx-power" the reason.

line 163: *status = HWREG(RFC_DBELL_BASE + RFC_DBELL_O_CMDSTA) & 0xFF;

if you get rid of  masking "& 0xFF" everything works fine again.

**Comment by g-oikonomou** [comment]
Any idea why? The E2E thread doesn't discuss the "why" either and I cannot see any logic in that. Are we certain this is a proper fix and not an accidental one?

**Comment by g-oikonomou** [comment]
Also, any idea exactly which command cause this?

**Comment by chenek** [comment]
After I build and download binary into my CC1310DK, it just keeps reboot. There is no command to trigger this.

**Comment by g-oikonomou** [comment]
I mean the code tries to send a command to the RF and the code gets stuck there waiting forever. I am wondering whether it's the first command or if it's a particular one.

Thanks for reporting this!

**Comment by g-oikonomou** [comment]
@chenek please, can you check with #1479?

**Comment by chenek** [comment]
I don't have access to my CC1310DK. I will test this on Tuesday and report back to you. Thanks for notifying us about this patch.

**Comment by chenek** [comment]
I have tested on this patch and it doesn't reboot now
