### ISSUE TITLE
Way to pause or stop RPL?

### ISSUE THREAD

**Issue by aldorianmode** [contiki-os/contiki#1499]
Hello everyone, 

As the title says, there is a way to pause or stop RPL? Im on a project that because of hardware limitations, can't use the radio and manage a device via UART at the same time. Trying to turn the radio off works for a little while but it seems that RPL turn it on again. 

I'd be gratefull for any idea or suggestion,

Aldo

**Comment by matfu2** [comment]
The flag CONTIKI_WITH_RPL defaults is set to default to 1 in Makefile.include . 
To remove RPL, specify "CONTIKI_WITH_RPL=0" in the console when make-ing, or put "CONTIKI_WITH_RPL=0" in a project makefile.

**Comment by aldorianmode** [comment]
Thanks for the quick answer @matfu2 :) maybe i wasn't entirely clear with my question but the thing is I need to pause and resume RPL on runtime. Is possible to do that?

**Comment by matfu2** [comment]
Unfortunately, I can't find any built-in way to disable/re-enable RPL at runtime.

**Comment by LanshunNie** [comment]
RPL is triggered by etimer. If you stop etimer, RPL stops.

**Comment by aldorianmode** [comment]
Thanks for the help. For the purpose i needed to pause/stop RPL, its not necessary anymore. I could turn off the radio using NETSTACK_MAC.off(0) using contikimac. With nullrdc i couldn't do the same, must investigate why.

**Comment by oddeyed** [comment]
Just curious - did you try NETSTACK_RDC.off(0)? Any good MAC layer should pass that down though.

**Comment by hafss** [comment]
Hello, i have changed the RDC driver to contikimac, but i have always nullrdc in mote outeput window of cooja simulator:
 **671613:1:nullsec CSMA nullrdc, channel check rate 128 Hz, radio channel 26, CCA threshold -45**
Should i turn off the radio using NETSTACK_RDC.off(0)?
