### ISSUE TITLE
cc1200 zoul MAX TX POWER

### ISSUE THREAD

**Issue by lovelesh** [contiki-os/contiki#1500]
I was going through the cc1200 datasheet and it suggests max TX power as 16 dBm but the cc1200 drivers suggests the max limit of 14 dBm. Does the code work with 16 dBm?

**Comment by uknoblic** [comment]
Hi,
for shure the code will work - but maybe the hardware will not ;-). 14 dBm comes from the limits given by the Europen regulations.



Ulf
