### ISSUE TITLE
Documentation Update :: Using github pages to host Doxygen documentation of Contiki

### ISSUE THREAD

**Issue by remyleone** [contiki-os/contiki#152]
I think it would be interesting to use Github pages (http://pages.github.com/) in order to host the Doxygen HTML documentation of Contiki online. Maybe having a git post-commit script that will build the html version of the documentation and push it to the gh-pages branch in the right folder.

I can work on this if people think it's a good idea ;-)

**Comment by ledlo** [comment]
On the main contiki website the Doxygen documentation point to version 2.6 of contiki, compiled in 2012.

**Comment by tonnenpinguin** [comment]
Travis is building the documentation with every build anyway - any chance that we can sync it to some location with every master-branch build?

**Comment by oliverschmidt** [comment]
However if you do so you should _not_ push it to the gh_pages branch of the "main" repository. This will increase the size of the Git repository in a way you don't want - as I learned the hard way.

For https://github.com/cc65/cc65 I therefore created an additional GitHub project in the same organization (that has an empty master branch) located at https://github.com/cc65/doc/tree/gh-pages and showing up at http://cc65.github.io/doc/. If that repo becomes too large I can just reset it.

The doc is created by Travis and pushed to "the other" GitHub project by the logic at https://github.com/cc65/cc65/blob/master/Makefile.travis#L11

Setting this up is somewhat complicated as you need a https://docs.travis-ci.com/user/environment-variables/#Encrypted-Variables for a GitHub token and you need to make _sure_ that it doesn't end up in build logs. See lines 13 and 14 in the Makefile linked above.

**Comment by tonnenpinguin** [comment]
I hear you. I've never setup one, but how about syncing it some external service like [readthedocs](https://readthedocs.org/)?

**Comment by oliverschmidt** [comment]
Thanks for the link.

Anyway I image no matter where you put the docs if you want to make sure that not "everybody" can upload updated docs you need some password / token /<...>. And that needs to be used by Travis in a secure way...

**Comment by SoonSYJ** [comment]
Sorry. I just want to know why there are no srf06-cc26xx platform in the latest doxygen. Thank you.

**Comment by cmorty** [comment]
@SoonSYJ Please don't ask off topic questions -> Use the mailing list or open a new issue or check the doxygen code, fix it and make a pull request.
