### ISSUE TITLE
Getting unix time stamp in Contiki OS for TI Sensortag 2.0

### ISSUE THREAD

**Issue by weijian19391** [contiki-os/contiki#1521]
Hi 

May i know if it's possible to get a unix timestamp in the sensortag, i.e. to synchronize the time of the sensortag with the world?

**Comment by g-oikonomou** [comment]
Impossible, unless you yourself implement some networking protocol that allows your sensortag to sync with an external time sourc (e.g. NTP). We don't have that at the moment.

**Comment by weijian19391** [comment]
@g-oikonomou I see. Thank you!
