### ISSUE TITLE
Which SPI implementation should be used with srf06-cc1310?

### ISSUE THREAD

**Issue by rafaeldelucena** [contiki-os/contiki#1527]
Hello,

I want to test the SPI with Contiki on the SRF06-CC1310. I found that in Contiki SensorTag has implemented board-spi.h and board-spi.c, It seems to me to be reusable for cc1310.

It is possible to use the same implementation for cc1310? Or I'll have to map the macros from (core/dev/spi.h) into calls for Texas Instruments (cpu/cc26xx-cc13xx/ti-lib.h) library?

Best Regards

**Comment by g-oikonomou** [comment]
Those two files should indeed be usable across boards. See for example what we've done in #1485 (the files you are referring to are being moved to a `common` dir.
