### ISSUE TITLE
MacOS upload contiki project to TI SensorTag2.0

### ISSUE THREAD

**Issue by SoonSYJ** [contiki-os/contiki#1551]
Any one please give me some advice about how can I upload an contiki code to my sensor tag

**Comment by IRandomPizza** [comment]
# Seting up Contiki development with the Sensortag(cc26xx) + Devpack for OSX Document

## Instaling the requied dependencies
You will need to install macports, Xcode befor continuing. The following will install arm-gcc for compling the code and srecord is used to conver from .ihex to hex
```bash
sudo xcodebuild -license
xcode-select --install
sudo port install arm-none-wabi-gcc srecord
```
You will also need to install Energia (it is an ardino equivelnt for Ti's microcontrollers) as it containes a tool called DSlite wich is used to flash the generated hex file onto the sensortag through the debug port. 
[Dowload location of Energia](http://energia.nu/download/)

Once dowloaded place in you Applications folder. 

## Compiling your first program
There are many ways to do this depending how you like to develop. For people useing base contiki there are many guides for this eg. https://github.com/contiki-os/contiki/tree/master/platform/srf06-cc26xx

## Putting .hex or .elf file onto sensortag 
The DSlite tool is currently located in:
```bash
/Applications/Energia.app/Contents/Resources/Java/tools/common/DSLite/DebugServer/bin/DSLite
```
To see the posable commands that you can use with DSlite go:
```bash
/Applications/Energia.app/Contents/Resources/Java/tools/common/DSLite/DebugServer/bin/DSLite help
```
Assumeing you are in the folder where the .hex or .elf file is located use the following command:
```bash
/Applications/Energia.app/Contents/Resources/Java/tools/common/DSLite/DebugServer/bin/DSLite load -c /Applications/Energia.app/Contents/Resources/Java/tools/common/DSLite/DebugServer/CC2650F128_TIXDS110_Connection.ccxml -f {File to load on device}
```
The output should look like:
```bash
Configuring Debugger (may take a few minutes on first launch)...
	Initializing Register Database...
	Initializing: IcePick_C
	Executing Startup Scripts: IcePick_C
	Initializing: CS_DAP_0
	Executing Startup Scripts: CS_DAP_0
	Initializing: Cortex_M3_0
	Executing Startup Scripts: Cortex_M3_0
GEL: Cortex_M3_0: GEL Output: Memory Map Initialization Complete.
Connecting...
GEL: Cortex_M3_0: GEL Output: Board Reset Complete.
Loading Program: hdc1000_test.elf
	Preparing ... 
	.text: 0 of 49680 at 0x0
	.text: 28672 of 49680 at 0x0: 55%
	.data: 0 of 88 at 0x1ffa8: 99%
	Finished: 99%
	Setting PC to entry point.: 99%
Running...
Success
```
