### ISSUE TITLE
Simulating 6LoWPAN network in COOJA

### ISSUE THREAD

**Issue by svnesbo** [contiki-os/contiki#1558]
Hi,

I have some CC2650/CC1310 code that I want to simulate in a large mesh network, so I have adapted the code for COOJA since there is no native CC2650/CC1310 mote type.

The code compiles but when I simulate I can't seem to get the motes to talk to one another. I have shaved away most of the code so I'm left with a minimal example, which I have attached. For my application I am interested knowing about the neighboring nodes, so the code prints out the neighbor table when the button is pressed.

I've tried compiling this code with 
**make cooja-test.cooja TARGET=cooja**
I've tried with a variety of settings for NETSTACK_CONF_RADIO/FRAMER/RDC etc. with no luck. I've also tried compiling for cooja-ip64, but that didn't work either.

This is the output from the motes when they start:
899	ID:3	Contiki-3.x-2220-g8f9ff51 started. Node id is set to 3.
899	ID:3	Rime started with address 0.3.0.3.0.3.0.3
899	ID:3	MAC 00:03:00:03:00:03:00:03 sicslowpan/CSMA/nullrdc, channel check rate 1000 Hz
899	ID:3	Tentative link-local IPv6 address fe80:0000:0000:0000:0203:0003:0003:0003
899	ID:3	Tentative global IPv6 address fd00:0000:0000:0000:0203:0003:0003:0003
899	ID:3	Starting 'Cooja Test - Main Process'
1024	ID:3	Got network connection.

If I push the button on one of the motes, I get this (no neighbors are printed, ie. there are none):
3601239	ID:2	Button pressed
3601239	ID:2	My IP: 100:fd00::202:2:2
3601239	ID:2	Neighbor table:

The radio messages window shows that the motes are sending ICMPv6 RPL DIS messages, but nothing else. Here are some example messages:
6001238	2	1,3,4,5	 27: 15.4 D 00:02:00:02:00:02:00:02 0xFFFF|IPHC|IPv6|ICMPv6 RPL DIS|0000
6001717	5	1,2,3,4	 27: 15.4 D 00:05:00:05:00:05:00:05 0xFFFF|IPHC|IPv6|ICMPv6 RPL DIS|0000

Can someone please help me get this working? I'm using contiki commit ID 3.x-2220-g8f9ff51, with no local changes. 

[cooja-test.zip](https://github.com/contiki-os/contiki/files/177667/cooja-test.zip)

**Comment by alignan** [comment]
Please send to the contiki maling list instead if you need help or advise.
