### ISSUE TITLE
link layer ACKNOWLEDGE is valid for UDP payload or not

### ISSUE THREAD

**Issue by bbhagasra1** [contiki-os/contiki#1561]
if(packetbuf_holds_broadcast()) {
    params.fcf.ack_required = 0;
  } else {
    params.fcf.ack_required = packetbuf_attr(PACKETBUF_ATTR_MAC_ACK);
  }

there is only check for target type......not for packet protocol type.

**Comment by joakimeriksson** [comment]
This is on link layer - if you do broadcast UDP there will be no ack (and should not be) - but if you do unicast there will be an ack. So yes - UDP gets a "valid" ack if it is unicast - but it is only a link layer ack.
