### ISSUE TITLE
UART communication between collect view and UDP-sink crashed.

### ISSUE THREAD

**Issue by LanshunNie** [contiki-os/contiki#1563]
Hi, all,
RPL-collect and collect view is very good for tesing and observing the behavior of network. 
We use it a lot in our project. It works quite well most of the time. However, the UART communication between collect view and UDP-sink occasionally crashed and the UDP-Sink node could not push data to PC. I wonder what may cause this happen. Also, is SLIP/TUNSLIP still a reliable solution since it also rely on Serial Communication? Any help or advice on this will be appreciated. 
Thank you. 
Lanshun

**Comment by alignan** [comment]
Could you please at least paste the error or try to provide more information?

**Comment by LanshunNie** [comment]
Thanks alignan.
The most difficult part is we can not get any error information, : (
When it crashed, the terminal of Ubuntu does not refresh any more.
Then we attached the root node to another PC and tried to read something from it, nothing came out.
The happiness also seems to be random. 
So I am totally lost in finding the reason. We use a platform based on MSP430F5418A+ CC1120. 

Would you please just tell me whether tunslip and SLIP is widely used in practical WSN project and works reliably?
Thanks again.

**Comment by alignan** [comment]
When it crashes, does the device has been assigned a new USB port?  for example if you used `/dev/ttyUSB0` it ends up assigned to `/dev/ttyUSB1` or alike?

You could always assign your device an `udev` rule so it always is assigned to a given port, and use applications like `supervisor` to re-launch the `tunslip6` script if crashes.  Google both alternatives.

**Comment by LanshunNie** [comment]
Thanks alignan. 
I think this is quite helpful. Will check and try it.

**Comment by alignan** [comment]
Great, thanks! If you happen to find any indication about what might went wrong, please re-open or make a PR!
