### ISSUE TITLE
mqtt-demo.c undefined reference to cc2538_temp_sensor and vdd3_sensor

### ISSUE THREAD

**Issue by asati1995** [contiki-os/contiki#1577]
I have copied all the contents of contiki/cpu/cc2538 to contiki/examples/cc2538dk/mqtt-demo
[mqtt-demo.txt](https://github.com/contiki-os/contiki/files/199178/mqtt-demo.txt)

![error-trace](https://cloud.githubusercontent.com/assets/15675041/14201263/5afd8fc0-f80e-11e5-9dc7-fb162ec69de6.PNG)

**Comment by alignan** [comment]
There is specific cc2538 code in the mqtt-demo, how do you expect to compile for a totally different platform?  You need to remove specific cc2538 components, and probably refactor the example as it will not fit the RAM as it currently is.

**Comment by asati1995** [comment]
Thanks for your help
