### ISSUE TITLE
Travis failing due to arm-gcc version no longer being available

### ISSUE THREAD

**Issue by g-oikonomou** [contiki-os/contiki#1586]
Since #1504 we are explicitly specifying what version of the toolchain to use for the travis arm job. Unfortunately, this version is no longer available on the PPA, apt fails to install it and the test falls over.

We can obviously revert the change from #1504 but then we will go back to the previous situation of travis using a different toolchain version than the one we specify in various READMEs. We have already agreed that we don't want that.

I've not 100% made up my mind how we want to fix this. @bthebaudeau @alignan any thoughts?

**Comment by g-oikonomou** [comment]
Thinking aloud: One option is to forget about apt altogether and wget the desired linux tarball from launchpad.net.

**Comment by alignan** [comment]
I was going to suggest the same.

**Comment by bthebaudeau** [comment]
:+1: for `wget`.
