### ISSUE TITLE
ISSUES WITH RPL-COLLECT ON Z1 MOTES DURING SIMULATION

### ISSUE THREAD

**Issue by Dmi10000** [contiki-os/contiki#1595]
I have followed your link and this is exactly the scenario we wish to create (one sink and several senders) for two scenarios. 1) For pure simulation of Z1 sensor motes as provided on InstantContiki and 2) for the testing of the physical motes (purchased) in a similar situation. The idea is to be able to use the data collected from the physical motes tested as a validation system for the simulation of our software simulation in step 1). Now with Contiki, the collect-view on Z1 does not work for simulation of these motes but works well for SKY motes. However, with the emulation (physical testing of motes) it does work. We want a situation were we could have both situations working for effecting comparison of results for both the simulation and the physical deployment of these Z1 motes.

This issue has to do with the Contiki platform. No sensor data or network communication details are displayed or collected using Collect-view in Contiki. 

Please any help will be welcome.

**Comment by alignan** [comment]
Not enough information to go on, as already discussed privately, it is unlikely someone is to test from scratch hoping to find something broke.  Re-Open when you provide information on what to look for (error, debug logs, etc), and how to reproduce.
