### ISSUE TITLE
can i determine the directory for the file in cfs ?

### ISSUE THREAD

**Issue by Ghada1M** [contiki-os/contiki#1596]
i have been searching for how can i write to file in contiki ,, and found this example ,,
https://github.com/contiki-os/contiki/wiki/Coffee-filesystem-example

my question is can i determine the file directory ? ,, also i couldn't fine the location of the file that we written in in the above example ?

I am beginner in contiki os ^_^

**Comment by g-oikonomou** [comment]
https://github.com/contiki-os/contiki/wiki#help
