### ISSUE TITLE
cc26xxware update

### ISSUE THREAD

**Issue by tonnenpinguin** [contiki-os/contiki#1600]
Hi all!

TI has released three cc26xxware updates over the past months. Is there a specific reason for the contiki maintenance team not to update the submodule? Otherwise I could prepare a pull request with the updated cc26xxware/cc13xxware version.

**Comment by g-oikonomou** [comment]
Very simply because I've not had the chance to test if everything works properly, or whether such update would also require changes on our side.

**Comment by tonnenpinguin** [comment]
alright, I'll give it a try and I'll open a pull request as soon as I've got something ready.
Thanks for the quick update!
