### ISSUE TITLE
Looking for Simplified Er-Rest Example for investigate Security of Coap

### ISSUE THREAD

**Issue by suspirik** [contiki-os/contiki#1603]
Hi all,

Is there anyone worked on CoAP security and applied a simple example?

I only need to focus on security so need a simple client and server example. And also security implementations, if you know any repository for these subjects which you can suggest me that would be great!

Thanks in advance...

**Comment by abuammarhashmi** [comment]
www.shahidraza.info/resources/CoAP-DTLS.zip

**Comment by abuammarhashmi** [comment]
am also working on coap security, tinydtls library may be of your help.

Clone: https://git.eclipse.org/r/tinydtls/org.eclipse.tinydtls
