### ISSUE TITLE
About webserver ipv6 example

### ISSUE THREAD

**Issue by suspirik** [contiki-os/contiki#1617]
Hi all,

I am a beginner in IoT and I will work on Security in CoAP. I needed a basic example and I decided to go on webserver example. I am using cc2531 and cc2650 and 6lbr now. So I will work on a real testbed and I have some questions regarding to the example https://github.com/contiki-os/contiki/blob/master/examples/webserver-ipv6/README.md ;

1) At first step there is written that UIP_CONF_TCP  settings of platform, is the platform "srf06-cc26xx" ? Or am I wrong?
2) I receive the error below 
user@instant-contiki:/etc/6lbr/platform/srf06-cc26xx/sensortag$     ifconfig tap0 inet6 3ffe:0501:ffff:0100:0206:98ff:fe00:0231
Don't know how to set addresses for family 10.
Do you have any suggestion to solve it?

3) and it suggests this settings on radvd  but I could not find any such file under "srf06-cc26xx" so should I use another platform for that? AdvPreferredLifetime 400;
  AdvValidLifetime 600; 

Since I will use real test bed I am confused between platforms like cooja ans sky. I found the radvd conf file under that platforms but not sure about if that platforms needed.

4) I want to implement get put methods between client and server, so is there any detailed example for that implementation which you can recommend ?

Thanks in advance...

**Comment by alignan** [comment]
https://github.com/contiki-os/contiki/wiki#Help
