### ISSUE TITLE
Can contiki mote get real-world time?

### ISSUE THREAD

**Issue by wufucious** [contiki-os/contiki#1649]
In my project, all sensors need to know real-world time, say "dd/mm/year, 12:12", when they produce and store data. Any suggestion? Examples? 

From my pointof view, all Contiki time library is usefulness because none of them are designed to get real-world time value.

**Comment by alignan** [comment]
We have this for the `RE-Mote` using an on-board RTCC:
https://github.com/contiki-os/contiki/tree/master/examples/zolertia/zoul/rtcc

Other alternative would be to poll the date to a NTP server.

You are welcome to contribute.

**Comment by marco-pistone** [comment]
i had implemented the conversion of unix time polled from my border router, It is not accurate to the second, but it is sufficient to my needs

**Comment by vsaw** [comment]
FYI: (sort of) Duplicate of #1648

**Comment by g-oikonomou** [comment]
I consider this to have been answered. Closing
