### ISSUE TITLE
RSSI-Scanner example broken, Offset wrong

### ISSUE THREAD

**Issue by bakashinji** [contiki-os/contiki#1664]
After the CC2420 driver itself adds its offset the values coming out of the RSSI-Scanner for the JAVA applets are wrong. Easy Fix: replace the 55 offset with 100 (adding RSSI_OFFSET)

**Comment by alignan** [comment]
Yes, I have also noticed this and did a similar fix [in my examples](https://github.com/alignan/contiki/commit/75bb439e46d52f2c2a7242af1ce7c2ddf46206a4)
