### ISSUE TITLE
Application apps/orchestra possible bug

### ISSUE THREAD

**Issue by warner83** [contiki-os/contiki#1671]
Hello, 
in the function new_time_source within the file orchestra-rule-unicast-per-neighbor.c (line 169) the function remove_uc_link is called. 
However, the argument is new_addr, shouldn't it be the address of the old time source?
@simonduq can you comment on this?

Thanks!

**Comment by simonduq** [comment]
It does look like a bug yes. Note that this implementation of Orchestra is not as much tested as the original one (https://github.com/simonduq/orchestra). Thanks for reporting!

**Comment by simonduq** [comment]
fixed via https://github.com/contiki-os/contiki/pull/1672
