### ISSUE TITLE
Error while uploading code!.

### ISSUE THREAD

**Issue by akshaypm** [contiki-os/contiki#1681]
I am trying to upload a code since a month and i am getting one or the other error from travis every time i upload. i have tried 6 to seven times prior to this the same code was uploaded successfully, with no errors please resolve this issue. Every time before i upload code i compile and test the code as well

**Comment by alignan** [comment]
Please provide more info about what error are you getting, is this about the `rpl-large` test failing?  If the regression test fails and it is unrelated to your changes, at the moment request a contributor to restart the failing job.
