### ISSUE TITLE
Unable to compile Cooja in Contiki-3.0 

### ISSUE THREAD

**Issue by jimmytmathew** [contiki-os/contiki#1685]
BUILD FAILED
/home/user/Downloads/contiki-3.0/tools/cooja/build.xml:199: The following error occurred while executing this line:
/home/user/Downloads/contiki-3.0/tools/cooja/apps/mspsim/build.xml:29: -
----------------
Could not find the MSPSim build file. Did you run "git submodule update --init"?
----------------

**Comment by jimmytmathew** [comment]
Got the solution. Check the link
https://sourceforge.net/p/contiki/mailman/message/34660437/

**Comment by adnanrashidpk** [comment]
The following worked for me:

1. Download the **mspsim** separately from this link _https://github.com/contiki-os/mspsim_ (check your _home/contiki/tools/mspsim_ and _home/contiki-3.0/tools/mspsim_ directories, both are probably empty).
2. Remove the empty **mspsim** directory from both places
3. After unzip **mspsim-master**, paste the unzipped **mspsim-master** directory on both places
4. Rename the directory from **mspsim-master** to **mspsim** on both palces.
5. Go to terminal (_user@instant-contiki:~/contiki-3.0/tools/cooja$_) and run this command _ant run_
6. No need to use _sudo_

Enjoy!
