### ISSUE TITLE
nRF52 DK breaks Travis CI

### ISSUE THREAD

**Issue by bthebaudeau** [contiki-os/contiki#1699]
Since the merger of #1469:
https://travis-ci.org/contiki-os/contiki/jobs/134588774

There is an issue (temporary or not) with the chosen PPA.

**Comment by alignan** [comment]
Dang! it was worked when tested some weeks ago... I'll try to fix (or disable the travis job), but reassigning to @wbober (the platform maintainer) for a better solution.

**Comment by alignan** [comment]
I just opened a PR with a proposed fix, I will open later an issue for pending things to change in the `nrf52dk` port.
