### ISSUE TITLE
CC2650 Sensortag Web Demo continuously rebooting

### ISSUE THREAD

**Issue by Rasfumi** [contiki-os/contiki#1722]
After pulling in the latest changes from contiki master branch the web-demo example is continuously rebooting. After disabling the watchdog i found out that after about 20 seconds the CPU gets stuck in FaultISR(). It seems it has something to do with the Pull request #1684. As this happens when trying to access a power domain that is disabled. In this case the AUX PD is off as i can see from Registers view.

**Comment by g-oikonomou** [comment]
Hi @Rasfumi 

I see you have deleted some stuff from the OP compared to your original post, something about your own application that used to work. As such, I cannot immediately understand whether you are using the example as-is, or whether you have local modifications. Have you made any changes whatsoever to the example?

I am now trying with SmartRF + CC2650EM and I cannot see anything strange.

**Comment by g-oikonomou** [comment]
I'm not seeing any problems with the sensortag either. I'll let it run for a while though.

**Comment by Rasfumi** [comment]
Hi @g-oikonomou 
thank you for your fast reply. In my own Application I found out it was my mistake that led to that infinite loop waiting for the HW Sempaphore.  I am using the Sensorcontroller and registered aux_ctrl consumer too late. For comparing to a working program i downloaded a fresh copy of contiki and tried the web-demo example which led to the result described. I only commented out the watchdog_start() in contiki-main.c to see where it hangs.
I just tried it again with the same result. Build command: make clean TARGET=srf06-cc26xx BOARD=sensortag/cc2650 cc26xx-web-demo.bin
It starts blinking fast, then connects to my 6lbr, blinks slower then stops blinking for a few seconds before rebooting.  (watchdog enabled again)
I am using TI CodeComposer  and compiler "gcc-arm-none-eabi-4_9-2015q3" with the DebugDevPack. A setup which used to work before.

**Comment by g-oikonomou** [comment]
Please, can you try with 5.2.1 20151202 (the one used by travis)

https://github.com/contiki-os/contiki/tree/master/platform/srf06-cc26xx#requirements

**Comment by Rasfumi** [comment]
I tried using the specified compier (5.2.1 20151202) and it really makes a difference, i even cross checked it. No more rebooting now. BUT with the newer compiler i cant access the sensortag through COAP or Web even it shows up in 6lbr. Other motes with older versions of contiki can be accessed though. Very strange...

**Comment by g-oikonomou** [comment]
Smells like this might be unrelated. Are you using latest 6lbr too? I suspect this could have to do with 6lo address compression contexts.

**Comment by Rasfumi** [comment]
i am using 6lbr 1.4.0 on raspberry PI connected to a CC2538-CC2592 Board with a slightly modified (RF-Amp Control) contiki version (latest commit 2016-04-07).

**Comment by Rasfumi** [comment]
I agree that the connection problem has nothing to do with #1684. Anyway its a strange behavior and i still have no idea what causes it. I have updated my slip-radio with the latest contiki, but as expected this didnt help. Lets see if other users have the same problem.
Thanks alot for your help and the work you are doing for the community!

**Comment by g-oikonomou** [comment]
See also #1573 and #1593, these could help.
