### ISSUE TITLE
Example cc26xx-demo Continually Reboots with Latest Contiki

### ISSUE THREAD

**Issue by davidjnix** [contiki-os/contiki#1744]
The cc26xx-demo on the SmartRF06 Eval Board reboots every 12 seconds or so. I am using the latest pull (f0b19a1). There was a similar report (#1465) from January 2016 that was resolved at that time. I verified that the fix for #1465 is in my repo. The serial output below demonstrates the reboot.

Starting Contiki-3.x-2647-gf0b19a1
With DriverLib v0.44336
TI SmartRF06EB + CC26xx EM
 Net: sicslowpan
 MAC: CSMA
 RDC: ContikiMAC, Channel Check Interval: 16 ticks
 RF: Channel 25
 Node ID: 34057
CC26XX demo
-----------------------------------------
Bat: Temp=25 C
Bat: Volt=3292 mV
ALS: 687 raw
Starting Contiki-3.x-2647-gf0b19a1
With DriverLib v0.44336
TI SmartRF06EB + CC26xx EM
 Net: sicslowpan
 MAC: CSMA
 RDC: ContikiMAC, Channel Check Interval: 16 ticks
 RF: Channel 25
 Node ID: 34057
CC26XX demo
-----------------------------------------
Bat: Temp=25 C
Bat: Volt=3292 mV
ALS: 685 raw

**Comment by g-oikonomou** [comment]
What toolchain version are you using?

**Comment by g-oikonomou** [comment]
I can confirm this. I suspect it's something to do with #1709

**Comment by g-oikonomou** [comment]
Can you try with `#define CC2650_FAST_RADIO_STARTUP 0`?

You can change the respective line in `contiki-conf.h` or set it in `project-conf.h`

**Comment by davidjnix** [comment]
George,


Will do later today. Thanks for the quick response.

David


________________________________

**Comment by davidjnix** [comment]
That fixed the issue. Verified using (f0b19a1) with SmartRF06 Eval Board and toolchain gcc-arm-none-eabi-5_2-2015q4.
