### ISSUE TITLE
Pointing to a Local MQTT Broker

### ISSUE THREAD

**Issue by birdmanhoo** [contiki-os/contiki#1772]
I have the Contiki web demo running on a CC2650 and I'm trying to troubleshooting MQTT and want to make sure I'm properly pointing the node to a local MQTT broker (Mosquitto). Is there anything else I need to do but change the broker IP on the node to the bbbb:: IPv6 address of the broker? I've tested publishing and subscribing between Linux machines using the bbbb:: IPv6 address and it is working. Is there anything I need to do with the Org Id or auth token? Thanks in advance.

**Comment by g-oikonomou** [comment]
https://github.com/contiki-os/contiki/wiki#Help
