### ISSUE TITLE
Cannot see UART output on CC1310 LaunchPad

### ISSUE THREAD

**Issue by chenek** [contiki-os/contiki#1773]
I pull the latest code and test with cc26xx-web-demo and hello-world examples. However, I cannot see UART output on CC1310 LaunchPad. Is this a bug?

**Comment by g-oikonomou** [comment]
@chenek I just tested current master with a CC1310 LP, UART output seems fine (input too).

What OS are you using? Are you looking at the correct port/tty?

**Comment by chenek** [comment]
Just verify this and find it works now. Thanks for your help.
