### ISSUE TITLE
[RPL-TSCH example] /examples/ipv6/rpl-tsch/node.c : TSCH: only scanning on channels

### ISSUE THREAD

**Issue by lawpeter** [contiki-os/contiki#1785]
Here is some information about my experimental: 
OS: ContikiOS
Scenario: Run **contiki/examples/ipv6/rpl-tsch/node.c**  [TSCH+RPL] 
I compiled file node.c -->  node.bin and transfer node.bin into OpenMotes **cc2538dk**.
However, when I capture packets on COM ports (I connect OpenBase to PC through COM port). 
The results show that TSCH only scanning the channels. 
The log file is below. 
I hope to receive some feedbacks to fix problems. 
Thank you very much. 

0167 R [13:08:28'826] : TSCH: scanning on channel 20
0166 R [13:08:27'761] : TSCH: scanning on channel 15
0165 R [13:08:25'798] : TSCH: scanning on channel 20
0164 R [13:08:24'892] : TSCH:! not associated, drop outgoing packet
0163 R [13:08:23'783] : TSCH: scanning on channel 25
0162 R [13:08:19'752] : TSCH: scanning on channel 20
0161 R [13:08:17'736] : TSCH: scanning on channel 15
0160 R [13:08:16'736] : TSCH: scanning on channel 20
0159 R [13:08:14'720] : TSCH: scanning on channel 26
0158 R [13:08:13'705] : TSCH: scanning on channel 15
0157 R [13:08:12'705] : TSCH: scanning on channel 20
0156 R [13:08:11'689] : TSCH: scanning on channel 26
0155 R [13:08:10'689] : TSCH: scanning on channel 25
0154 R [13:08:09'673] : TSCH: scanning on channel 15
0153 R [13:08:07'658] : TSCH: scanning on channel 26
0152 R [13:08:06'658] : TSCH: scanning on channel 15
0151 R [13:08:05'642] : TSCH: scanning on channel 26
0150 R [13:08:04'642] : TSCH: scanning on channel 15
0149 R [13:07:59'595] : TSCH: scanning on channel 20
0148 R [13:07:56'580] : TSCH: scanning on channel 25
0147 R [13:07:54'564] : TSCH: scanning on channel 15
0146 R [13:07:52'548] : TSCH: scanning on channel 20
0145 R [13:07:51'533] : TSCH: scanning on channel 15
0144 R [13:07:50'533] : TSCH: scanning on channel 26
0143 R [13:07:49'501] : TSCH: scanning on channel 15
0142 R [13:07:48'501] : TSCH: scanning on channel 25
0141 R [13:07:47'486] : TSCH: scanning on channel 20
0140 R [13:07:46'486] : TSCH: scanning on channel 25
0139 R [13:07:45'470] : TSCH: scanning on channel 20
0138 R [13:07:44'470] : TSCH: scanning on channel 15
0137 R [13:07:43'455] : TSCH: scanning on channel 25
0136 R [13:07:42'455] : TSCH: scanning on channel 26
0135 R [13:07:41'439] : TSCH: scanning on channel 15
0134 R [13:07:39'423] : TSCH: scanning on channel 25
0133 R [13:07:38'423] : TSCH: scanning on channel 15
0132 R [13:07:37'408] : TSCH: scanning on channel 26
0131 R [13:07:36'408] : TSCH: scanning on channel 15
0130 R [13:07:35'392] : TSCH: scanning on channel 26
0129 R [13:07:34'392] : TSCH: scanning on channel 25
0128 R [13:07:33'376] : TSCH: scanning on channel 26
0127 R [13:07:30'361] : TSCH: scanning on channel 20
0126 R [13:07:29'345] : TSCH: scanning on channel 25
0125 R [13:07:28'876] : --- Network status ---
 Server IPv6 addresses:
- fe80::212:4b00:615:a4c7
- Default route:
  -- None
## \- Routing entries (0 in total):

0124 R [13:07:28'345] : TSCH: scanning on channel 20
0123 R [13:07:27'345] : TSCH: scanning on channel 15
0122 R [13:07:26'330] : TSCH: scanning on channel 20
0121 R [13:07:25'330] : TSCH: scanning on channel 25
0120 R [13:07:24'892] : TSCH:! not associated, drop outgoing packet

**Comment by thomas-ha** [comment]
You need to have a root node running with the role 6dr. The other nodes, the 6ln nodes, then will associate to the network built by the root node.
