### ISSUE TITLE
Contiki crashes when calling NETSTACK_RADIO.off()

### ISSUE THREAD

**Issue by jcole123** [contiki-os/contiki#1799]
I'm running Contiki on a custom 5x5mm board and everything is working with the exception of turning the radio off. It looks like CMD_ABORT in rx_off (ieee-mode.c) is causing it to crash, which is odd because rf_core_send_cmd returns RF_CORE_CMD_OK when it's called, but if I run rx_off with CMD_ABORT commented out it doesn't crash. I've tested the radio in SmartRF studio as well as Contiki with 100% duty cycle and I'm able to send/receive with no issues.

**Comment by g-oikonomou** [comment]
https://github.com/contiki-os/contiki/blob/master/platform/srf06-cc26xx/README.md

> This port is only meant to work with 7x7mm chips
