### ISSUE TITLE
MSP430 flash size problems (travis)

### ISSUE THREAD

**Issue by marcas756** [contiki-os/contiki#1803]
Travis reports an issue with read only memory allocation  for pull request #1801 which actually I think has nothing to do with MSP430.

https://travis-ci.org/contiki-os/contiki/jobs/148516185

/usr/local/bin/../lib/gcc/msp430/4.7.2/../../../../msp430/bin/ld: region `rom' overflowed by 2 bytes

Just wanted to mention it, that it does not get forgotten.

**Comment by g-oikonomou** [comment]
And I only just noticed this one, which I shall now close.

#1808, #1809

**Comment by marcas756** [comment]
accepted ;-)
