### ISSUE TITLE
Managing network with RPL

### ISSUE THREAD

**Issue by aignacio** [contiki-os/contiki#1811]
Hello all,

I'm new user of Contiki and I'm testing some examples with MQTT-SN on CC2650, basically I'm using rpl_border_router with SLIP connected to the Linux that runs my broker. Considering that Contiki uses the RPL protocol for routing the nodes, how can I get the status of links, nodes, active devices, tracking packages and others resources to create a map of healthy of my network? Sorry for the ignorant question but after searching for answers I just found the collect-view example that does not make clear how to integrate with my scenario.... Is there some functions for managing the network?

**Comment by g-oikonomou** [comment]
https://github.com/contiki-os/contiki/wiki#Help
