### ISSUE TITLE
Multi hopping with custom IPv6 address | Contiki OS

### ISSUE THREAD

**Issue by kaleemullah360** [contiki-os/contiki#1812]
Hi all,

Working in `Contiki OS` and trying to create a network of multiple nodes.

using `Websense Example` in `Contiki OS` I'm requesting data from the mote which is 3-hops away from border router. all motes are at line of sight to each other and `TX` power is set to `0` which is `-37 (dBm)`.

the problem I am facing is connectivity issue, some time motes are not connected, and some time 4th mote is directly connected to border router, may be due to fresnal zone effect.

is there a way that I can specify a custom address in order to ensure that mote A is always connected to mote B not to any other.

please help me. how can I do that. Thank You very much.

**Comment by g-oikonomou** [comment]
https://github.com/contiki-os/contiki/wiki#Help
