### ISSUE TITLE
Question:Adding external sensor with cc2650 sensortag, implementing in cc26xx-web-demo

### ISSUE THREAD

**Issue by shosant** [contiki-os/contiki#1814]
Hi,
I am extending the application cc26xx-web-demo to include the new external sensor added to the cc26xx sensortag (I2c).
Is there any recommended iDE for compiling&debugging?
or Should I directly build the code in contiki?
Please advice, I am new to this.

**Comment by votrungchi108** [comment]
I think you should "directly build the code in contiki" use gcc-arm and makefile.
Best Regards,

**Comment by g-oikonomou** [comment]
https://github.com/contiki-os/contiki/wiki#Help
