### ISSUE TITLE
[CC1310] Can I fetch RSSI of packet transferred between 2 specific nodes in contiki 6lowpan network?

### ISSUE THREAD

**Issue by votrungchi108** [contiki-os/contiki#1818]
Hi everyone,

I want to fetch RSSI value of packet transferred between 2 nodes in contiki 6lowpan network. My setup as below:
- Use 6lbr as gateway (GW)
- Have 3 nodes in my network, called A, B, C. Currently, All of 3 nodes have parent is a GW.

I wanna fetch RSSI value of packet transferred from B to A so I make a ping() from A to B and get RSSI value when received ping reply packet. But this RSSI is not my expected, this is RSSI value of packet transferred from GW to A because routing of mesh network. (Packet transferred from parent to node).

I am looking for the way to send packet directly from B to A for get RSSI value.
1. Is able to do this on contiki platform?
2. How to do this on contiki platform?
3. Any suggestions for my facing problem?

And I have posted this issue on TI forum: http://e2e.ti.com/support/wireless_connectivity/zigbee_6lowpan_802-15-4_mac/f/158/t/535173

Thanks & Best Regards,
Chi Vo

**Comment by g-oikonomou** [comment]
https://github.com/contiki-os/contiki/wiki#Help
