### ISSUE TITLE
 can receive a packet from other Node even it's there packet in process

### ISSUE THREAD

**Issue by htm1112** [contiki-os/contiki#1840]
good evening every one,

I need to fined an answer for this question:  

is the Node can receive a packet from other Node even it's there packet in process?

thanks in advanced

**Comment by g-oikonomou** [comment]
https://github.com/contiki-os/contiki/wiki#Help

**Comment by htm1112** [comment]
I don't know why you not very helpful, if I have knowledge, I will share it with others. I know your think this issue very simple or easy but for other it may be big step. 
if you give me the right answer will help me a lot. 
sorry for inconvenient and thanks.

**Comment by alignan** [comment]
Posting an issue is not the right channel to ask for help, that is the purpose of the mailing list, it is not a matter of not be willing to help, but to avoid a misuse of the issue tracker.

**Comment by htm1112** [comment]
OK. I'm sorry for this.
