### ISSUE TITLE
serial_line_event_message not working in CC2650DK

### ISSUE THREAD

**Issue by di-mu** [contiki-os/contiki#1880]
Trying receiving serial message as demoed in https://github.com/contiki-os/contiki/wiki/Input-and-output

The serial line event is not fired when sending strings to the device.

**Comment by di-mu** [comment]
Alternatively, I managed the serial reading feature by cc26xx_uart_set_input function defined in contiki/cpu/cc26xx-cc13xx/dev/cc26xx-uart.h

**Comment by greg-king5** [comment]
> Alternatively, I managed the serial reading feature by using the `cc26xx_uart_set_input` function that's defined in `"dev/cc26xx-uart.h"`.

Actually, there is no generic/portable way to do it!

You found the correct way to do it on cc13xx and cc26xx platforms.
