### ISSUE TITLE
Thread program in contiki 

### ISSUE THREAD

**Issue by sinkarharshad** [contiki-os/contiki#1901]
I am not able to see output of my thread code in terminal window. 
When I run this same program in c, this code is working fine.
Please find below attached images for your reference.
Kindly help me to resolve this issue. Thank you in advance. 
![screen shot 2016-10-25 at 01 39 55](https://cloud.githubusercontent.com/assets/18270841/19667896/fddc5e96-9a53-11e6-815f-a7caa3800dfb.png)
[my-second-code.c.zip](https://github.com/contiki-os/contiki/files/549273/my-second-code.c.zip)

**Comment by g-oikonomou** [comment]
https://github.com/contiki-os/contiki/wiki#Help
