### ISSUE TITLE
CC1310 with Contiki

### ISSUE THREAD

**Issue by mario9876** [contiki-os/contiki#1926]
Hello everyone, I'm new in this area and would like to know some things. I'm working full-CC1310 of Smartrf06 and should be loaded inside contiki. Can anyone help me or show me some guidance? Thank you so much!

**Comment by g-oikonomou** [comment]
https://github.com/contiki-os/contiki/wiki#Help

**Comment by mario9876** [comment]
Hello I have seen this guide, but do not know how the CC1310 with a perfectionist gamers SmartRF06. can you help me?

**Comment by greg-king5** [comment]
You must ask "how to" questions on the mailing list (that wiki link tells you about it).

**Comment by mario9876** [comment]
How can I do? can you help me?
