### ISSUE TITLE
How to exit from Contiki code? 

### ISSUE THREAD

**Issue by sinkarharshad** [contiki-os/contiki#1930]
Please find below attached snapshot of my code output. Every time when I execute my code, I have to use ctrl+c (cmd+c) to exit. Is there any function in Contiki's library which will help me to resolve this issue?
Thank you in advance!!!

![screen shot 2016-11-09 at 16 13 50](https://cloud.githubusercontent.com/assets/18270841/20143123/052a2818-a698-11e6-9708-4f9d5e5e8e03.png)

**Comment by g-oikonomou** [comment]
https://github.com/contiki-os/contiki/wiki#Help

**Comment by sinkarharshad** [comment]
@g-oikonomou That did not solve my doubt. :!
