### ISSUE TITLE
Conversion map between PA_LEVEL and output power in dBm | CC2420

### ISSUE THREAD

**Issue by kaleemullah360** [contiki-os/contiki#1937]
### (from table 9 in CC2420 specification).

Can we use any other power level not defined in following table. i.e I want to use `power level 5` instead of 3, where as `power level 5` has no register value but `power level 3` has register value. 

### Source File:
dev/cc2420/cc2420.c:105

|dBm|Level|Register Val|
|---|---|---|
| 0 |31|0xff|
|-1 |27|0xfb|
|-3 |23|0xf7|
|-5 |19|0xf3|
|-7 |15|0xef|
|-10|11|0xeb|
|-15|7 |0xe7|
|-25|3 |0xe3|

**Comment by alignan** [comment]
You can change the code to replace as suitable for your testing (add a new tupple), or send a pull-request with the proposed changes :smile:
