### ISSUE TITLE
Contiki on VisualGDB or eclipse

### ISSUE THREAD

**Issue by juttTechnology** [contiki-os/contiki#1944]
hello,
         i saw everyone is using the Linux to Run this code.
         is there any possibility to run this code in VisualGDB or eclipse software.

        i have Nrf52dk.

thank you

**Comment by alignan** [comment]
Eclipse is an IDE, thus it can run on Windows, Linux, etc.

When you say "this code" no one will ever know which code you are referring to.  If you are talking about Contiki, then you should further look if the nrf52dk required toolchain is available in the OS you want to use (Windows, Linux, etc), then check information related to install Contiki on such OS.

Closing this issue, as this is a general question more pertinent to the contiki mailing list.
