### ISSUE TITLE
Go programming in contiki 

### ISSUE THREAD

**Issue by ronnie1233** [contiki-os/contiki#1946]
I want to work on Go program using contiki . Will it be compitable with the hardware i will work with ,

**Comment by alignan** [comment]
I haven't heard of any Go implementations, so that is unlikely.  Also it is _very_ difficult to know which hardware you are working with, if you don't provide a name.  Closing this issue.

**Comment by ronnie1233** [comment]
Hi there i am working with TI CC1310 hardware . Will it be possible with the implementation
