### ISSUE TITLE
CI java.lang.UnsupportedClassVersionError

### ISSUE THREAD

**Issue by simonduq** [contiki-os/contiki#1965]
CI tests involving java are currently broken:
https://travis-ci.org/contiki-os/contiki/builds

with error:
`Exception in thread "main" java.lang.UnsupportedClassVersionError: org/contikios/cooja/Cooja : Unsupported major.minor version 52.0`

**Comment by MohamedSeliem** [comment]
https://www.traviscistatus.com/incidents/nq0sf0srvx8s

 Travis is experiencing some issues in restoring OSX capacity, which may be the cause of such error.

**Comment by simonduq** [comment]
solved https://github.com/contiki-os/contiki/pull/1966
