### ISSUE TITLE
Tunslip6 broken on OS X?

### ISSUE THREAD

**Issue by MartinNPN** [contiki-os/contiki#1974]
Hello,

i actually testing tunslip6 at os x and found out that it didn't work. On a Linux VM it is working as expected but with OS X 10.12.1 it doesn't. 
First i fixed the compiler warning: 
tunslip6.c:135:3: warning: implicit declaration of function 'gettimeofday' is invalid in C99 [-Wimplicit-function-declaration]
by adding the correct header: 
#include <sys/time.h>

Maybe this could be corrected by someone.

But after that i startet with:
sudo ./tunslip6 -B 38400 -s /dev/tty.usbmodemXXXX fd00::1/64
and got:
********SLIP started on ``/dev/tty.usbmodemXXXX''
tunslip6: main: open /dev/tun: Is a directory

Is that a common problem ?
I can use open vpn under os x which although creates a tun device without any problems.

Has anyone an idea ?

Regards,
Martin

**Comment by greg-king5** [comment]
See issue #1560.

**Comment by MartinNPN** [comment]
Hello,

thanks, that solved the problem, i thought it is so old that it would be fixed already.
