### ISSUE TITLE
explicitly wrap c->last_originator_seqno to 0 in netflood when used for route-discovery

### ISSUE THREAD

**Issue by igurov** [contiki-os/contiki#198]
In route-discovery is the hddr->rreq_id an 8 bit integer. When continuously sending route-discovery requests, at some point this integer gets to 255 and wraps after that to 0, but the c->last_originator_seqno in netflood, which is a 16 bit integer, continues to increase after 255, which will cause the check if(!(rimeaddr_cmp(&hdr.originator, &c->last_originator) &&hdr.originator_seqno <= c->last_originator_seqno)) 
in netflood.c in function recv_from_polite to be always 0 after this point. In order to fix this, I had to explicitly wrap c->last_originator_seqno to 0 when it reaches 255.

**Comment by joakimeriksson** [comment]
This seems to have passed quite some time without any response. What about closing?

**Comment by alignan** [comment]
> quite some time

Indeed, but does this still applies? I tried searching at `core/net/rime/route-discovery.c` but couldn't find the check.

**Comment by joakimeriksson** [comment]
I would say that the maintainer of Rime is/was mainly @adamdunkels and I am not sure that he will spend too much time on that anymore. I am personally not using Rime since 5-6 years and based on the responses on this thread I guess there is not a lot of interest - or?
