### ISSUE TITLE
Struct uip_icmpip_hdr has no member named 'icmp6data'

### ISSUE THREAD

**Issue by juttTechnology** [contiki-os/contiki#2003]
Hello.
         i found one more issue in the uip.c file.
**uip.c Line # 1037**   
  **if(uip_ipaddr_cmp(&ICMPBUF->icmp6data, &uip_hostaddr))**
here you are calling the icmp6data. which is really not member of ICMPBUF.
please also confirm  the  options[,0] on line # 1039
flags,reserved1,reserved3,reserved3
you are calling all these members from the ICMPBUF, which they are not  belong to.

i have no idea how  you are compiling the code. why you are not getting the error on this kind of issues.

thank you ...

**Comment by greg-king5** [comment]
It is very old, "dead" code; Contiki never compiles it!
Look at https://github.com/contiki-os/contiki/blob/master/Makefile.include#L66-L101
That make-file will compile "ipv4/uip.c" only when we want IPv4; therefore, `NETSTACK_CONF_WITH_IPV6` will be "false".  `NETSTACK_CONF_WITH_IPV6` will be "true" only when we want IPv6.  Then, the make-file will compile "ipv6/uip6.c" instead.
