### ISSUE TITLE
How reduce the RAM data size 

### ISSUE THREAD

**Issue by juttTechnology** [contiki-os/contiki#2007]
i am using the simple_udp_rpl example.
i just simple add the all the required files into the visualgdb.
         Used FLASH: 172KB out of 512KB (33%)
         Used RAM: 36KB out of 64KB (57%) [+2280]
i am trying to reduce the RAM data from 36kb to 25kb.

here is my Symbol Table

SYMBOL TABLE:
20002a54 l    d  .bss   00000000 .bss
20002a54 l       .bss   00000001 completed.7620
20002a58 l       .bss   00000018 object.7625
20006dd4 l     O .bss   00000004 heap_end.5213
20002ca0 l     O .bss   00000010 registrations_memb_count
20002aa0 l     O .bss   00000200 registrations_memb_mem
20002a70 l     O .bss   00000004 own_services_list
20002a74 l     O .bss   00000004 others_services_list
20002a78 l     O .bss   00000001 started
20002a7c l     O .bss   00000010 sendtimer
20002a8c l     O .bss   00000004 outconn.11032
20002a90 l     O .bss   00000010 periodic.11031
20002cb0 l     O .bss   00000001 leds
20002cb4 l     O .bss   00000004 ptr.8072
20002cb8 l     O .bss   00000008 rxbuf
20002cc0 l     O .bss   00000080 buf.8071
20002d40 l     O .bss   00000001 overflow.8065
20002d41 l     O .bss   00000080 rxbuf_data
20002dc4 l     O .bss   00000004 i.8087
20002dc8 l     O .bss   00000001 num_sensors
20002dcc l     O .bss   00000004 events.8088
20002dd0 l     O .bss   00000004 callback
20002dd4 l     O .bss   00000001 uncomp_hdr_len
20002dd5 l     O .bss   00000001 packetbuf_hdr_len
20002dd8 l     O .bss   00000004 packetbuf_ptr
20002ddc l     O .bss   00000004 last_rssi
20002de0 l     O .bss   00000190 _ds6_neighbors_mem
20003154 l     O .bss   0000000a routememb_memb_count
20002fc4 l     O .bss   00000190 routememb_memb_mem
20002fc0 l     O .bss   00000002 defaultroutermemb_memb_count
20002f80 l     O .bss   00000040 defaultroutermemb_memb_mem
200031b0 l     O .bss   0000000a neighborroutememb_memb_count
20003160 l     O .bss   00000050 neighborroutememb_memb_mem
200031bc l     O .bss   00000050 _nbr_routes_mem
20002f70 l     O .bss   00000004 notificationlist_list
20002f74 l     O .bss   00000004 defaultrouterlist_list
20002f78 l     O .bss   00000004 num_routes
20002f7c l     O .bss   00000004 routelist_list
2000320c l     O .bss   00000004 locprefix
20003210 l     O .bss   00000004 locaddr
20003214 l     O .bss   00000004 locmaddr
20003218 l     O .bss   00000010 loc_fipaddr
20003228 l     O .bss   00000001 rscount
2000322c l     O .bss   00000004 echo_reply_callback_list_list
20003230 l     O .bss   00000010 tmp_ipaddr
20003240 l     O .bss   00000004 input_handler_list_list
20003244 l     O .bss   00000004 nd6_opt_llao
20003248 l     O .bss   00000001 nd6_opt_offset
2000324c l     O .bss   00000004 nbr
20003250 l     O .bss   00000004 nd6_opt_prefix_info
20003254 l     O .bss   00000004 prefix
20003258 l     O .bss   00000010 ipaddr
20003268 l     O .bss   00000004 addr
2000326e l     O .bss   00000002 lastport
20003270 l     O .bss   00000004 iss
20003275 l     O .bss   00000500 databuffer
20003775 l     O .bss   00000001 started
20003778 l     O .bss   00000010 periodic
20003788 l     O .bss   00000004 outputfunc
2000378c l     O .bss   000000a4 s
20003830 l     O .bss   00000078 _link_stats_mem
200038a8 l     O .bss   00000100 received_seqnos
20003a60 l     O .bss   0000000a neighbor_addr_mem_memb_count
200039e8 l     O .bss   00000078 neighbor_addr_mem_memb_mem
200039a8 l     O .bss   00000004 nbr_table_keys_list
200039ac l     O .bss   0000000a used_map
200039b8 l     O .bss   00000020 all_tables
200039d8 l     O .bss   00000004 num_tables
200039dc l     O .bss   0000000a locked_map
20003a6c l     O .bss   00000002 buflen
20003a6e l     O .bss   00000002 bufptr
20003a70 l     O .bss   00000500 packetbuf_aligned
20003f70 l     O .bss   00000001 hdrlen
200068f4 l     O .bss   00000008 buframmem_memb_count
20003f74 l     O .bss   00002980 buframmem_memb_mem
2000691c l     O .bss   00000008 bufmem_memb_count
200068fc l     O .bss   00000020 bufmem_memb_mem
20006924 l     O .bss   00000050 _rpl_parents_mem
20006974 l     O .bss   00000004 timer_init
20006978 l     O .bss   00000020 periodic_timer
20006998 l     O .bss   00000002 worst_rank
2000699c l     O .bss   00000004 worst_rank_nbr
200069a0 l     O .bss   00000004 num_parents
200069a4 l     O .bss   00000004 num_children
200069a8 l     O .bss   00000002 next_dis
200069ac l     O .bss   00000020 periodic_timer
200069cc l     O .bss   00000001 dio_send_ok
200069cd l     O .bss   00000001 mode
200069d0 l     O .bss   00000004 ctimer_list_list
200069d4 l     O .bss   00000001 initialized
200069d8 l     O .bss   00000004 timerlist
200069dc l     O .bss   00000004 next_expiration
200069e8 l     O .bss   00000001 poll_requested
200069e9 l     O .bss   00000001 lastevent
200069ea l     O .bss   00000001 fevent
200069eb l     O .bss   00000001 nevents
200069ec l     O .bss   00000180 events
20006b6c l     O .bss   00000004 next_rtimer
20006b70 l     O .bss   00000018 m_adv_params
20006b88 l     O .bss   00000004 busy_rx
20006b8c l     O .bss   0000000c interfaces
20006b98 l     O .bss   00000004 busy_tx
20006b9c l     O .bss   00000004 ticks
20006ba0 l     O .bss   00000004 uart0_input_handler
20006ba4 l     O .bss   00000001 rx_buffer
20006ba8 l     O .bss   00000008 txbuf
20006bb0 l     O .bss   00000080 txbuf_data
20006c30 l     O .bss   00000001 wdt_channel_id
20006c31 l     O .bss   00000001 wdt_initialized
20006c34 l     O .bss   00000040 btn_timer
20006c74 l     O .bss   00000004 btn_state
20006c78 l     O .bss   00000058 m_cb
20006cd0 l     O .bss   00000004 m_handlers
20006cd4 l     O .bss   00000003 m_cb
20006cd8 l     O .bss   00000002 m_swi_flags
20006cdc l     O .bss   00000004 m_swi_handlers
20006ce0 l     O .bss   00000001 m_drv_state
20006ce4 l     O .bss   00000001 m_cb
20006ce8 l     O .bss   00000004 mp_contexts
20006cec l     O .bss   00000004 m_timer_event_handlers
20006cf0 l     O .bss   00000018 m_cb
20006d08 l     O .bss   00000004 m_wdt_event_handler
20006d0c l     O .bss   00000001 m_state
20006d10 l     O .bss   00000004 m_alloc_index
20006d14 l     O .bss   00000001 m_softdevice_enabled
20006d18 l     O .bss   00000004 m_sys_evt_handler
20006d1c l     O .bss   00000004 m_ble_evt_handler
20006d20 l     O .bss   00000002 m_ble_evt_buffer_size
20006d24 l     O .bss   00000004 mp_ble_evt_buffer
20006d28 l     O .bss   00000004 m_evt_schedule_func
20006d2c l     O .bss   00000010 led_timer.13035
20006d3c l     O .bss   00000024 unicast_connection
20006d60 l     O .bss   00000010 periodic_timer.13104
20006d70 l     O .bss   00000010 send_timer.13105
20006d80 l     O .bss   00000004 message_number.13111
20006d84 l     O .bss   00000048 BLE_EVT_BUFFER.13043
20006dd8 l     O .bss   0000000c m_channel
20006de4 l     O .bss   00000004 m_evt_handler
20006de8 l     O .bss   00001400 m_rx_buffer
20002a54 l       .bss   00000000 __bss_start__
200092f4 l       .bss   00000000 __bss_end__
20008dd0 g     O .bss   00000001 ble_event_interface_deleted
20008d60 g     O .bss   00000030 energest_total_time
200081ec g     O .bss   000000c0 uip_ds6_if
200082ac g     O .bss   00000001 uip_ds6_netif_addr_list_offset
20008330 g     O .bss   00000002 uip_len
20008d90 g     O .bss   00000004 energest_total_count
200092f0 g     O .bss   00000004 errno
20002a54 g       .bss   00000000 _sbss
200069e4 g     O .bss   00000004 process_list
200082ad g     O .bss   00000001 uip_ds6_addr_size
20008334 g     O .bss   00000004 uip_sappdata
20008d94 g     O .bss   0000000c energest_current_mode
20008bd8 g     O .bss   00000010 packetbuf_addrs
20008338 g     O .bss   00000004 uip_acc32
200082b0 g     O .bss   00000060 uip_ds6_prefix_list
200092e4 g     O .bss   00000004 m_p_file_name
2000833c g     O .bss   00000008 uip_lladdr
20008344 g     O .bss   00000500 uip_aligned_buf
20008844 g     O .bss   00000001 uip_flags
20008bb0 g     O .bss   00000020 periodic_timer
20008310 g     O .bss   00000010 uip_ds6_timer_periodic
20008848 g     O .bss   00000004 uip_next_hdr
20008bd0 g     O .bss   00000008 linkaddr_node_addr
200092f4 g       .bss   00000000 _ebss
20008c08 g     O .bss   00000004 default_instance
2000884c g     O .bss   00000004 uip_udp_conn
200092f4 g       .bss   00000000 end
20008be8 g     O .bss   0000001e packetbuf_attrs
20008c0c g     O .bss   00000154 instance_table
200092e8 g     O .bss   00000004 m_error_code
20008850 g     O .bss   00000004 uip_appdata
20008854 g     O .bss   00000004 uip_conn
20008bac g     O .bss   00000001 tcpip_event
20008858 g     O .bss   000001e0 uip_conns
20008a38 g     O .bss   00000008 uip_icmp6_conns
20003274 g     O .bss   00000001 uip_ext_bitmap
20008a40 g     O .bss   00000028 uip_listenports
200092ec g     O .bss   00000004 m_line_num
20008da0 g     O .bss   00000030 energest_current_time
200069e0 g     O .bss   00000004 process_current
20008320 g     O .bss   00000010 uip_ds6_timer_rs
2000326c g     O .bss   00000001 uip_ext_len
200092de g     O .bss   00000006 sensors_flags
200081e8 g     O .bss   00000001 serial_line_event_message
2000326d g     O .bss   00000001 uip_ext_opt_offset
20008dd1 g     O .bss   00000001 ble_event_interface_added
20006dd0 g     O .bss   00000004 __malloc_sbrk_start
200081e9 g     O .bss   00000001 sensors_event
20006dcc g     O .bss   00000004 __malloc_free_list
20008bad g     O .bss   00000001 tcpip_icmp6_event
20008a68 g     O .bss   00000002 uip_slen
20008a6c g     O .bss   00000140 uip_udp_conns
20008dd2 g     O .bss   0000050c input_packet

any idea, how this can be achiveable ?

**Comment by darkopetrovic** [comment]
Set a lower value for the following parameter in your `project-conf.h` file: 

    #define UIP_CONF_BUFFER_SIZE 1300

**Comment by g-oikonomou** [comment]
There are plenty of discussions about this on the mailing list and there is also this: https://github.com/contiki-os/contiki/wiki/Reducing-Contiki-OS-firmware-size
