### ISSUE TITLE
Issue comparing serial numbers

### ISSUE THREAD

**Issue by aguirrem** [contiki-os/contiki#201]
I have brought this issue in the mailing list but it was posed as question more than a report. 

I believe there is an issue with the function lollipop_greater_than in [rpl-dag.c](https://github.com/contiki-os/contiki/blob/master/core/net/rpl/rpl-dag.c)

the following code, I believe, fails to fully implement the spec [rfc1982 sec 3.1](http://tools.ietf.org/html/rfc1982)  

``` c
static int
lollipop_greater_than(int a, int b)
{
  /* Check if we are comparing an initial value with an old value */
  if(a > RPL_LOLLIPOP_CIRCULAR_REGION && b <= RPL_LOLLIPOP_CIRCULAR_REGION) {
    return (RPL_LOLLIPOP_MAX_VALUE + 1 + b - a) > RPL_LOLLIPOP_SEQUENCE_WINDOWS;
  }
  /* Otherwise check if a > b and comparable => ok, or
     if they have wrapped and are still comparable */
  return (a > b && (a - b) < RPL_LOLLIPOP_SEQUENCE_WINDOWS) ||
    (a < b && (b - a) > (RPL_LOLLIPOP_CIRCULAR_REGION + 1-
			 RPL_LOLLIPOP_SEQUENCE_WINDOWS));
}
``` 

it appears the code implements the check specified in 7.2.2.1 of [rfc6550 ] (http://tools.ietf.org/html/rfc6550#section-7.2)

    2. In the case where both sequence counters to be compared are less than 
    or equal to 127, and in the case where both sequence counters to be compared 
    are greater than or equal to 128:

                 1.  If the absolute magnitude of difference between the two
                 sequence counters is less than or equal to
                 SEQUENCE_WINDOW, then a comparison as described in
                 [RFC1982] is used to determine the relationships greater
                 than, less than, and equal.

                 2.  If the absolute magnitude of difference of the two
                 sequence counters is greater than SEQUENCE_WINDOW, then a
                 desynchronization has occurred and the two sequence
                 numbers are not comparable.

Assuming that 2^(SERIAL_BITS - 1) == 127 I don't think the code implements the following specified in [rfc1982 sec 3.1](http://tools.ietf.org/html/rfc1982)  

    (i1 < i2 and i2 - i1 > 2^(SERIAL_BITS - 1)) or
    (i1 > i2 and i1 - i2 < 2^(SERIAL_BITS - 1))

Am I completely wrong here and missing something basic?

**Comment by g-oikonomou** [comment]
@nvt Nicolas, should we be flagging this one as a bug?

**Comment by joakimeriksson** [comment]
Lets show a counterexample where the code is doing wrong before we flag it as a bug. It is non-trivial to follow so possibly a rewrite of either comments or code might be good. But is there in fact an example of a and b where the code is wrong? (I have not tested it right now  - but I think we did when it was implemented).

**Comment by nvt** [comment]
Let's close the issue for now -- we can re-open it if some error cases are shown. Perhaps some unit tests should be set up for the lollipop counter, since it is non-trivial to verify its correctness by mere inspection.
