### ISSUE TITLE
CC2538: i2c: cannot issue a repeated start bit.

### ISSUE THREAD

**Issue by LucaZulberti** [contiki-os/contiki#2013]
Hi all!

I'm trying to use a temperature and humidity sensor (https://www.silabs.com/Support%20Documents/TechnicalDocs/Si7006-A20.pdf) with a CC2538 based board.

As the datatsheet states (page 23), to read the ID registers and the REV Number from the sensor, the master should send multiple START bits to perform the necessary read and wirte operations.

The I2C firmware provides 4 functions to perform read and write operations, but none of this leave the user the choice to add the STOP bit at the end of the transmission. I think this makes my attempts to read ID end REV fail.

To solve this issue I think the i2c functions should give the possibility to choose the presence of the STOP bit.

Thank you for your attention,

Luca.

**Comment by bthebaudeau** [comment]
Hi Luca,

Please have a look at i2c_master_command().

Best regards,
Benoît
