### ISSUE TITLE
CC26xx-web-demo unable to see sensorTag data on IBM quickstart

### ISSUE THREAD

**Issue by warisara** [contiki-os/contiki#2016]
I am following the procedure for the CC26xx web demo listed at http://processors.wiki.ti.com/index.php/Cc26xx_sw_examples.
I can open 6lbr web page ([bbbb::100]) and can open web page on cc2650.
 
![image](https://cloud.githubusercontent.com/assets/13960195/21437364/07f4bd3e-c8b6-11e6-922f-f8afce0ec0e6.png)

![image](https://cloud.githubusercontent.com/assets/13960195/21437387/1f51f4b0-c8b6-11e6-8481-ace3c42402d6.png)

but in IBM quickstart I can't see sensorTad data.

![image](https://cloud.githubusercontent.com/assets/13960195/21437423/4c5d7f24-c8b6-11e6-954c-2ecc50285ed6.png)

I try to sniff packet on BBB by use command '"sudo tcpdump -i eth0 -v -X port 1883". it show below.

![image](https://cloud.githubusercontent.com/assets/13960195/21437467/95cac1da-c8b6-11e6-8a6d-36764fc2c2aa.png)

but I still can't see data in IBM quickstart.
Can anyone know how to solve this problem? please.

//Warisara

**Comment by jonnteolsson** [comment]
The problem is in your NAT64 setup most probably. Using tcpdump -i eth0 -v -X port 1883 you should also see some IPv4 data, not only IPv6. Do you have the prefix for NAT64 correctly configured?

**Comment by warisara** [comment]
@jonnteolsson 

My wrapsix configuration is

/* +++ CONFIGURATION +++ */
#define INTERFACE       "eth0"
#define PREFIX          "64:ff9b::"
#define IPV4_ADDR       "192.168.1.3"
#define HOST_IPV6_ADDR  "bbbb::101"
#define HOST_IPV4_ADDR  "192.168.1.42"
/* --- CONFIGURATION --- */

192.168.1.42 is Beaglebones IPv4 address. this configure is correct?

//warisara

**Comment by chenek** [comment]
Actually, you don't have to run wrapsix if you run latest 6lbr which enable NAT64. You can follow the settings in the screen shot and do remember to set Peer router to IPv6 address of your desktop.

![config](https://cloud.githubusercontent.com/assets/14016565/21704345/a84d4448-d3f3-11e6-9c1b-848ad98b1a86.jpg)
