### ISSUE TITLE
Content-Format: 1541 problem with Contiki LWM2M and the latest Leshan releases

### ISSUE THREAD

**Issue by drugo72** [contiki-os/contiki#2036]
As of Leshan 0.1.11-M12 (M11 is the last one that works), temperature observations reported by the ``ipso-objects`` example are not properly decoded by Leshan that throws a null pointer exception.

The Contiki LWM2M implementation sends observations with ``Content-Format`` set to 1541 which is no longer supported/valid with the latest Leshan releases ([see this issue](https://github.com/eclipse/leshan/issues/155))

It seems that this can easily fixed by changing the default content format in a few places of ``lwm2m.engine.c`` from ``LWM2M_TEXT_PLAIN`` to just ``TEXT_PLAIN``.

This works however I'm not sure this is the proper fix.

Also, Leshan has updated the Content-Format codes for TLV and JSON ([see this issue](Content-Format)) so the ``Accept`` option now uses the new ones

**Comment by joakimeriksson** [comment]
Yes, that is more or less it, but we also need to be backwards compliant. We are working on a significant update of LWM2M and how it is integrated with CoAP. In this I recently added support for the new types. It is currently at a temporary repository at github.com:nfi/contiki-lwm2m.git .We aim to move it to a more official repository soon and upstream changes when we have a robust implementation. I am also working on a port to NodeMCU for the complete LWM2M engine from Contiki using the new codebase.

**Comment by drugo72** [comment]
Thanks. I'll give it a try.

**Comment by joakimeriksson** [comment]
Ok, if you have any questions just send me an email!
