### ISSUE TITLE
[curses.h] problem in native platform

### ISSUE THREAD

**Issue by sieben** [contiki-os/contiki#204]
I get the following error in a numerous amount of examples with a simple make : 

cc -DPROJECT_CONF_H=\"project-conf.h\" -DCONTIKI=1 -DCONTIKI_TARGET_NATIVE=1 -Wall -g -I/usr/local/include  -O  -I. -I../../..//platform/native/. -I../../..//platform/native/dev -I../../..//platform/native/ctk -I../../..//cpu/native/. -I../../..//cpu/native/net -I../../..//core/dev -I../../..//core/lib -I../../..//core/net -I../../..//core/net/mac -I../../..//core/net/rime -I../../..//core/net/rpl -I../../..//core/sys -I../../..//core/cfs -I../../..//core/ctk -I../../..//core/lib/ctk -I../../..//core/loader -I../../..//core/. -I../../..//apps/antelope -I../../..//platform/native/ -DCONTIKI_VERSION_STRING=\"Contiki-2.6-487-g96e85cc\" -MMD -c ../../..//platform/native/ctk/ctk-curses.c -o obj_native/ctk-curses.o
../../..//platform/native/ctk/ctk-curses.c:34:20: erreur fatale: curses.h : Aucun fichier ou dossier de ce type
compilation terminée.
make: *** [obj_native/ctk-curses.o] Erreur 1

**Comment by wasifhamdani** [comment]
Thumbs up fambon

**Comment by klandari** [comment]
Thanks fambon! it works!
