### ISSUE TITLE
cc26xx-web-demo : Change MQTT configuration failed

### ISSUE THREAD

**Issue by warisara** [contiki-os/contiki#2042]
I am following the procedure for the CC26xx web demo listed at http://processors.wiki.ti.com/index.php/Cc26xx_sw_examples.
then I can see data on IBM quickstart. 

![image](https://cloud.githubusercontent.com/assets/13960195/21837375/3ebb6e7e-d7fe-11e6-9f59-25f480b65258.png)

I want to create app on IBM platform by use data on IBM quickstart 
I try to change  Org ID from quickstart to my Org ID and add Auth Token then device disconnected on IBM quickstart but in my app it's not connect too.

![image](https://cloud.githubusercontent.com/assets/13960195/21837470/d60ce01e-d7fe-11e6-88eb-3d5ab82e1e2b.png)

what should I do?

Warisara

**Comment by g-oikonomou** [comment]
I vaguely remember reading something about Org IDs on Watson, somewhere. Can you check watson docs, will it still accept Org ID + Token in unencrypted MQTT messages?

**Comment by warisara** [comment]
@g-oikonomou 

 when I try tutorials on IBM watson platform it have to use this information :
- tcp://<org-id>.messaging.internetofthings.ibmclound.com
- port : 1883
- org
- device type
- device id
- token

but in MQTT/IBM Cloud Config web it's difference.

![image](https://cloud.githubusercontent.com/assets/13960195/21924009/b4509306-d9a9-11e6-92d8-e889a907c532.png)



Warisara

**Comment by warisara** [comment]
@g-oikonomou 

Maybe it can't do?

![image](https://cloud.githubusercontent.com/assets/13960195/21925733/5268df06-d9b1-11e6-9ab7-5baaae646522.png)

**Comment by g-oikonomou** [comment]
I think you may have to first register the device with Watson.

https://console.ng.bluemix.net/docs/services/IoT/devices/mqtt.html

**Comment by g-oikonomou** [comment]
Any updates on that one?

**Comment by MarCast** [comment]
Hi, I working with CC13xx with MQTT. I open IBM Watson but I not read the value. Can you help me?
