### ISSUE TITLE
Question: rpl- multiple instance

### ISSUE THREAD

**Issue by shosant** [contiki-os/contiki#2049]
Hi, 
Is multiple instance implementation of RPL (also multiple dag in an instance?) is possible is Contiki?

Thanks .

**Comment by g-oikonomou** [comment]
https://github.com/contiki-os/contiki/wiki#Help

**Comment by darkfader** [comment]
Set RPL_CONF_MAX_INSTANCES to something other than 1. I haven't tried it though.

**Comment by philok93** [comment]
Has anyone tried the above solution? I have tried it but nodes couldn't join even the default instance. Any help please?
