### ISSUE TITLE
Free application for NXP KW41Z development kit,ContikiOS new platfrom

### ISSUE THREAD

**Issue by EEworldForum** [contiki-os/contiki#2051]
The FRDM-KW41Z is a development kit enabled by the Kinetis® W series KW41Z/31Z/21Z (KW41Z) family built on ARM® Cortex®-M0+ processor with integrated 2.4 GHz transceiver supporting Bluetooth® Smart/Bluetooth®Low Energy (BLE) v4.2, Generic FSK, IEEE® 802.15.4 and Thread.
The FRDM-KW41Z kit contains two Freedom boards that can be used as a development board or a shield to connect to a host processor. The FRDM-KW41Z is form-factor compatible with the Arduino™ R3 pin layout for more expansion options.

[>>Click here to apply for free](http://bbs.eeworld.com.cn/huodong.php?id=242)
[>>点击此处，免费申请KW41开发套件](http://bbs.eeworld.com.cn/huodong.php?id=242)

If you have any trouble for application，conact me:
QQ:2804024537
Email：bbs_service@eeworld.com.cn
Tel：（010）82350740
如在申请时遇到任何问题，可通过以上方式联系我。

**Comment by alignan** [comment]
Spam!
