### ISSUE TITLE
control wsns with SDN controller

### ISSUE THREAD

**Issue by mokli** [contiki-os/contiki#2068]
Hi everyone,
I am newly in contiki. I want to connect an SDN controller (such as ONOS) to a wsn network and control my wsn with the SDN controller can any one help me to establish this connection?

**Comment by BigMikes** [comment]
You could do that with the RPL-border-router example. Try to follow this guide: http://anrg.usc.edu/contiki/index.php/RPL_Border_Router

But be careful, ONOS assumes to talk using OpenFlow protocol, which must be implemented inside the sensor node.

**Comment by mokli** [comment]
Thank you dear, can you tell me how can I implement open flow protocol in WSN?

**Comment by alignan** [comment]
Use the Contiki mailing list to ask for help, the issue tracker is to report problems

**Comment by amirinia** [comment]
> 
> 
> Thank you dear, can you tell me how can I implement open flow protocol in WSN?

Did you find the solution?
