### ISSUE TITLE
Maximum Packet size in 868MHZ 

### ISSUE THREAD

**Issue by amar22** [contiki-os/contiki#2086]
Hi Everyone,

I am working on 868 MHZ radio , I am trying to push 8 ipso resources, out of them i am able to see 3 resources on lwm2m server. How i can solve this issue.

Thanks
Amar Garg

**Comment by nvt** [comment]
We would need a more concrete specification of what setup of the official codebase is required to reproduce the problem. Help can be found in more appropriate places pointed out in https://github.com/contiki-os/contiki/wiki#Help
