### ISSUE TITLE
Max packet size in 868MHZ

### ISSUE THREAD

**Issue by amar22** [contiki-os/contiki#2088]
Hi Everyone,
I am working on 868 MHZ radio , I am trying to push 8 ipso resources, out of them i am able to see 3 resources on lwm2m server.
All 8 IPSO resources working with 2.4ghz , I need information how to work it on 868Mhz
Appreciate for responses 

Thanks
Amar Garg

**Comment by nvt** [comment]
Duplicate issue -- closing.
