### ISSUE TITLE
Icreasing flash size for storing data

### ISSUE THREAD

**Issue by vitarico** [contiki-os/contiki#2092]
Hey everyone!

I am working with the sensortag cc2650. 
I want to store some data on the flash over a peroid of time using the ext_flash_write(); function. 

```
rv = ext_flash_open();

  if(!rv) {
    pritnf("Error opening flash\n");
    ext_flash_close();
    return;
  }
  rv = ext_flash_erase(CONFIG_FLASH_OFFSET, sizeof(ahdc));

  if(!rv) {
    printf("Error erasing flash\n");
  } 
  else {
    rv = ext_flash_write(CONFIG_FLASH_OFFSET, sizeof(ahdc), (uint8_t *)&ahdc);
  }

 ext_flash_read(CONFIG_FLASH_OFFSET, sizeof(ahdc), (uint8_t *) ahdc));
```

Everything works fine so far. If i get it right, I can store 4kByte on the flash but I want to use the cc2650 Sensortag as a simple data logger for temperature and humidity. Meaning storing 4 byte every minute over 3 days so I do need a lot of space. As I read the data over UART I don't need any wireless communication. I am really new to embedded programming so I am a bit afraid to touch the makefile or the config files without proper guidance. I would really appreciate any help on how to reduce the the storage needed for the code and how to allocate more space on the flash for the data. 

Thank you a lot!

Victoria

**Comment by g-oikonomou** [comment]
I'm not really sure what you mean by "Allocate more space on flash for the data". The external flash on your sensortag has a fixed size and all of it is available to you for your logging, we don't use it for anything else (other than some basic configuration in the web demo).

Further, this is more of a "How do I?" issue, so I'm closing this: https://github.com/contiki-os/contiki/wiki#Help
