### ISSUE TITLE
NULL RDC is not working

### ISSUE THREAD

**Issue by iampradiptaghosh** [contiki-os/contiki#2112]
upon using nullrdc_driver the unicast not working. with rdc it is working fine. but when I turn of rdc, it is not even sending any radio packets and the unicast callback is returning with a status of 5 which is the default status.

**Comment by chitrung218ulsan** [comment]
I think, you firstly should check if the packet is received at packet_input function in nullrdc.c. Then, you continue to debug at upper layers.
