### ISSUE TITLE
TI cc2530dk serial reading failure with hello-world example

### ISSUE THREAD

**Issue by zhangysh1995** [contiki-os/contiki#2113]
I followed 8051 wiki to run this program, but cannot read the "hello world" sentence in console. 

Before I post here, I tried PuTTY and Tera Term on Windows and minicom on linux. The device with SmartRF05 EB is recognized as Cebal controlled devices on Windows and is not recognized as MTP devices on Instant Contiki. And also there is no support for "make login" on this platform.

I appreciate any suggest that may help me with this problem.

**Comment by g-oikonomou** [comment]
https://github.com/contiki-os/contiki/wiki#Help
