### ISSUE TITLE
How to make a connection between 2 devices CC2650 using bluetooth?

### ISSUE THREAD

**Issue by kstheart** [contiki-os/contiki#2130]
I used Contiki to develop cc2650, I want to use bluetooth to connect cc2650, but i can't find useful thing in Contiki.  I just found BLE beacon in the cc26xx-demo .

Should  I  use some open source bluetooth stack in Contiki  ?

**Comment by chenek** [comment]
As I know, there is no enough FLASH size on CC2650 to run both Contiki OS and full BLE Stack. This means you can only enable BLE beacon within Conitki for CC2650.

**Comment by g-oikonomou** [comment]
Contiki does not feature a BLE stack at the moment (other than some work on IPv6 over BLE for the nrf52dk platform). So you'd need a fair bit of work to make this work.

**Comment by tsparber** [comment]
Maybe this PR https://github.com/contiki-os/contiki/pull/1936 of @spoerk is of intereset.
