### ISSUE TITLE
Cooja MspCLI can not execute the the "start" and "stop" commands .

### ISSUE THREAD

**Issue by yulincoder** [contiki-os/contiki#2136]
Hello,
When i type the 'start' command in MspCLI, the simulation did not start.

![10qtpj 4a49asjpp7j8ey](https://cloud.githubusercontent.com/assets/10429180/23882956/dfdaea48-089e-11e7-8ec4-84a9464b5997.png)

When the simulation is already running then i type the 'stop' command, the information will been given that "CPU is not running
command 'stop' failed with error code 1"

![qq 20170314102048](https://cloud.githubusercontent.com/assets/10429180/23883115/f25a65bc-089f-11e7-9c4c-f24396e01f9e.png)

I use sky mote and main.exe complied by tinyos.

Thank you.

**Comment by joakimeriksson** [comment]
Some of the CLI commands are only useful when MSPSim is running “standalone” and not
when integrated into another framework such as COOJA. In COOJA the simulator controls
all the running instances of MSPSim so there is no point trying to stop or start one single node.



On 14 Mar 2017, at 03:26, ZhangT <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello,
When i type the 'start' command in MspCLI, the simulation did not start.

[10qtpj 4a49asjpp7j8ey]<https://cloud.githubusercontent.com/assets/10429180/23882956/dfdaea48-089e-11e7-8ec4-84a9464b5997.png>

When the simulation is already running then i type the 'stop' command, the information will been given that "CPU is not running
command 'stop' failed with error code 1"

[qq 20170314102048]<https://cloud.githubusercontent.com/assets/10429180/23883115/f25a65bc-089f-11e7-9c4c-f24396e01f9e.png>

I use sky mote and main.exe complied by tinyos.

Thank you.

**Comment by yulincoder** [comment]
Thanks very much.
