### ISSUE TITLE
Unable to cause Fragmentation 

### ISSUE THREAD

**Issue by Shridharfly** [contiki-os/contiki#2141]
I am using latest build of contiki.

I have just added the following lines [here][3].

    #define SICLOWPAN_CONF_FRAG 1
    #define UIP_CONF_BROADCAST 1
    #define UIP_CONF_REASSEMBLY 1
    #define NETSTACK_CONF_WITH_IPV6 1	
    #define UIP_CONF_IPV6_REASSEMBLY 1	
    #define UIP_CONF_UDP 1

I have done no other changes to any of the files.

I want to force fragmentation. Irrespective of whether SICSLOWPAN_CONF_FRAG is enabled, the control reaches [this][1] line.

I have experimented with various values for [MAX_PAYLOAD_LEN][2] but I could not force fragmentation.

I noticed that large packets are not delivered, but are not fragmented.

What is the minimum MAX_PAYLOAD_LEN at which fragmentation should happen?
How do I make fragmentation happen?

  [1]: https://github.com/contiki-os/contiki/blob/3f4436bac9a9f6da0df188372d4374693eab8a52/core/net/ipv6/sicslowpan.c#L1479
  [2]: https://github.com/contiki-os/contiki/blob/94854177e2837a6dec0e19624887165aa7cec7d5/examples/ipv6/rpl-udp/udp-client.c#L61
  [3]: https://github.com/contiki-os/contiki/blob/master/examples/ipv6/rpl-udp/project-conf.h

**Comment by BigMikes** [comment]
Probably you should increase also the size of the buffer content here:
`sprintf(buf, "Hello %d from the client", seq_id);`

**Comment by Shridharfly** [comment]
Thanks for the reply @BigMikes !
Instead of [this](https://github.com/contiki-os/contiki/blob/94854177e2837a6dec0e19624887165aa7cec7d5/examples/ipv6/rpl-udp/udp-client.c#L111) I tried  

`uip_udp_packet_sendto(client_conn, buf, MAX_PAYLOAD_LEN, &server_ipaddr, UIP_HTONS(UDP_SERVER_PORT));` 

But no success.

**Comment by greg-king5** [comment]
You don't need to define `NETSTACK_CONF_WITH_IPV6`; the makefiles define it.

You might need to increase the size of the uIP buffer, so that it can hold your bigger payload.  Define a big-enough `UIP_CONF_BUFFER_SIZE` in the "project-conf.h" file (it needs to hold at least the payload and a header).

It looks as though you don't need much to trigger fragmentation.  Try payloads that are multiples of 128.

**Comment by Shridharfly** [comment]
I was increasing size of payload but I partially fed data into buffer. As soon as I fed a lot of data in complete buf, the issue was solved.
