### ISSUE TITLE
Difference between rpl-udp, udp-ipv6 and net-uart

### ISSUE THREAD

**Issue by masb3** [contiki-os/contiki#2154]
Could anyone clarify differences between \examples\ipv6\rpl-udp, \examples\udp-ipv6 and \examples\cc26xx\cc26xx-web-demo\net-uart?

For me it looks same, but I believe there are some specifics that I can't determine.

**Comment by g-oikonomou** [comment]
https://github.com/contiki-os/contiki/wiki#Help
