### ISSUE TITLE
Outdoor mesh range with the CC1310

### ISSUE THREAD

**Issue by jbartlett12026** [contiki-os/contiki#2177]
I am running the 6lbr border router demo using CC1310s and following the http://processors.wiki.ti.com/index.php/Cc26xx_sw_examples and have stable running connections indoors. However, when I go outside to test, the connections are hardly established at a meter distance. I am using duck antennas on the nodes and slip radio and I wonder if it is a factor of the output power. I noticed that there have been issues with the CC1310 RF driver, but is there any way to better control transmitting output power?

**Comment by g-oikonomou** [comment]
Try with #1931 and #1932 (I'll be merging them in a few days).

**Comment by g-oikonomou** [comment]
@jbartlett12026 what's the status here. Is this working better for you or shall we keep this open?

**Comment by jbartlett12026** [comment]
@g-oikonomou Yes it is! For those using CC1310 LPs: There were three things that seemed to increase range/connectivity. Using null_rdc over contiki_mac, using the #1932 pull over the main, and changing the VDDH register to broadcast at 14dbm.

**Comment by g-oikonomou** [comment]
Fantastic. Closing

**Comment by g-oikonomou** [comment]
I am still unhappy with the fact that nullrdc increases range - this shouldn't be happening. I think the radio behaves differently shortly after power up compared to when it's been running for a while. We need to figure this out...
