### ISSUE TITLE
Q: How can I achieve RPL_PARENT_COUNT macro functionality.

### ISSUE THREAD

**Issue by omerfirmak** [contiki-os/contiki#2178]
There used to be a _parents_ list in _rpl_dag_ struct and a corresponding macro for counting the elements in _parents_ list in the earlier versions of Contiki.

Is there any way to achieve RPL_PARENT_COUNT macros functionality with the current set of functions provided?

**Comment by g-oikonomou** [comment]
https://github.com/contiki-os/contiki/wiki#Help
