### ISSUE TITLE
How to calculate throughput and delay of XMAC protocol in Cooja simulation tool?

### ISSUE THREAD

**Issue by gsoni260** [contiki-os/contiki#2196]
I want to compare XMAC and ContikiMAC protocol on the basic of throughput and deley on cooja simulation tool(contiki os), So i want to know how can i calulate throughput and deley of above mention protocol in cooja tool.

**Comment by nvt** [comment]
That is not an issue for this tracker. See https://github.com/contiki-os/contiki/wiki#Help
