### ISSUE TITLE
Using collect-view

### ISSUE THREAD

**Issue by Shridharfly** [contiki-os/contiki#2200]
I am trying to use [collect-view][1] in my program. 

If I do not include `CONTIKI_WITH_IPV6 = 1` in makefile I get the following error:

    client.co: In function `input_packet':
    /home/user/contiki/examples/ipv6/Attack/../../../core/./net/mac/sicslowmac/sicslowmac.c:164: undefined reference to `uip_flags'
    /home/user/contiki/examples/ipv6/Attack/../../../core/./net/mac/sicslowmac/sicslowmac.c:166: undefined reference to `uip_appdata'
    /home/user/contiki/examples/ipv6/Attack/../../../core/./net/mac/sicslowmac/sicslowmac.c:166: undefined reference to `uip_len'
    /home/user/contiki/examples/ipv6/Attack/../../../core/./net/mac/sicslowmac/sicslowmac.c:50: undefined reference to `button_sensor'
    /home/user/contiki/examples/ipv6/Attack/../../../core/./net/mac/sicslowmac/sicslowmac.c:216: undefined reference to `uip_lladdr'
    /home/user/contiki/examples/ipv6/Attack/../../../core/./net/mac/sicslowmac/sicslowmac.c:216: undefined reference to `uip_ds6_set_addr_iid'
    /home/user/contiki/examples/ipv6/Attack/../../../core/./net/mac/sicslowmac/sicslowmac.c:222: undefined reference to `uip_ds6_addr_add'
    /home/user/contiki/examples/ipv6/Attack/../../../core/./net/mac/sicslowmac/sicslowmac.c:244: undefined reference to `uip_ds6_if'
    /home/user/contiki/examples/ipv6/Attack/../../../core/./net/mac/sicslowmac/sicslowmac.c:261: undefined reference to `uip_ds6_if'
    /home/user/contiki/examples/ipv6/Attack/../../../core/./net/mac/sicslowmac/sicslowmac.c:261: undefined reference to `uip_debug_ipaddr_print'
    /home/user/contiki/examples/ipv6/Attack/../../../core/./net/mac/sicslowmac/sicslowmac.c:266: undefined reference to `uip_ds6_get_link_local'
    /home/user/contiki/examples/ipv6/Attack/../../../core/./net/mac/sicslowmac/sicslowmac.c:157: undefined reference to `udp_new'
    /home/user/contiki/examples/ipv6/Attack/../../../core/./net/mac/sicslowmac/sicslowmac.c:283: undefined reference to `udp_broadcast_new'
    /home/user/contiki/examples/ipv6/Attack/../../../core/./net/mac/sicslowmac/sicslowmac.c:305: undefined reference to `uip_debug_ipaddr_print'
    /home/user/contiki/examples/ipv6/Attack/../../../core/./net/mac/sicslowmac/sicslowmac.c:333: undefined reference to `button_sensor'
    /home/user/contiki/examples/ipv6/Attack/../../../core/./net/mac/sicslowmac/sicslowmac.c:180: undefined reference to `dis_output'
    /home/user/contiki/examples/ipv6/Attack/../../../core/./net/mac/sicslowmac/sicslowmac.c:375: undefined reference to `uip_ds6_defrt_choose'
    /home/user/contiki/examples/ipv6/Attack/../../../core/./net/mac/sicslowmac/sicslowmac.c:375: undefined reference to `uip_ds6_defrt_lookup'
    /home/user/contiki/examples/ipv6/Attack/../../../core/./net/mac/sicslowmac/sicslowmac.c:375: undefined reference to `uip_ds6_route_head'
    /home/user/contiki/examples/ipv6/Attack/../../../core/./net/mac/sicslowmac/sicslowmac.c:375: undefined reference to `uip_ds6_route_nexthop'
    /home/user/contiki/examples/ipv6/Attack/../../../core/./net/mac/sicslowmac/sicslowmac.c:375: undefined reference to `uip_ds6_route_next'
    /home/user/contiki/examples/ipv6/Attack/../../../core/./net/mac/sicslowmac/sicslowmac.c:375: undefined reference to `tcpip_event'
    /home/user/contiki/examples/ipv6/Attack/../../../core/./net/mac/sicslowmac/sicslowmac.c:375: undefined reference to `tcpip_event'
    /home/user/contiki/examples/ipv6/Attack/../../../core/./net/mac/sicslowmac/sicslowmac.c:247: undefined reference to `uip_udp_packet_sendto'
    /home/user/contiki/examples/ipv6/Attack/../../../core/./net/mac/sicslowmac/sicslowmac.c:283: undefined reference to `uip_udp_packet_send'
    /home/user/contiki/examples/ipv6/Attack/../../../core/./net/mac/sicslowmac/sicslowmac.c:311: undefined reference to `uip_udp_packet_sendto'
    collect2: error: ld returned 1 exit status
    make: *** [client.exp5438] Error 1

If I do not include `CONTIKI_WITH_RIME = 1` in makefile I get the following error:

    ../../../apps/shell/shell-netstat.c: In function ‘process_thread_shell_netstat_process’:
    ../../../apps/shell/shell-netstat.c:118:13: error: ‘uip_conns’ undeclared (first use in this function)
    ../../../apps/shell/shell-netstat.c:118:13: note: each undeclared identifier is reported only once for each function it appears in
    make: *** [obj_exp5438/shell-netstat.o] Error 1
    Process returned error code 2

How do I get rid of the error?

  [1]: https://github.com/contiki-os/contiki/blob/master/examples/collect/collect-view-shell.c

**Comment by nvt** [comment]
See examples/ipv6/rpl-collect/ for a correct usage of Collect View. This question pertains to an unknown directory "Attack", so this is more of a support question rather than a Contiki issue -- closing.
