### ISSUE TITLE
Make login issue

### ISSUE THREAD

**Issue by mfk31** [contiki-os/contiki#2301]
Dear Sir,
I have uploaded the code on openmote-cc2538 but couldn't be able to login 
while writing command login I am getting following errors
make: *** No rule to make target `login'.  Stop.
 may please suggest how can I see the output on console

**Comment by sumanpanchal** [comment]
@mfk31 
Try this:
https://github.com/contiki-os/contiki/pull/2302

**Comment by mfk31** [comment]
Thanks its working!

**Comment by sumanpanchal** [comment]
Nice!! Close this issue now.
