### ISSUE TITLE
cc2538dk cannot use collect-view

### ISSUE THREAD

**Issue by yoyo890121** [contiki-os/contiki#2313]
I want to use `collect-view` to visualize my network topology so I tried `collect-view-shell` , but `collect-view` cannot find any connected motes. And I tried `motelist-linux`, the same as "No devices found".

I tried `rpl-border-router`  and used `tunslip6` connect to mote, it could work.

How do I get rid of the error? or Is there any other way to use `collect-view`?
Thanks.

**Comment by lamnd09** [comment]
To my best knowledge, we only can use collect-view application with sky motes. It doesn't support cc2538dk at this time.

**Comment by prodomo** [comment]
there is the guide of collect-view
http://anrg.usc.edu/contiki/index.php/Collect_View
could use command "make TARGET=cc2538dk" to produce .bin
P.S. it should have highest priority for step 4

**Comment by yoyo890121** [comment]
Thanks for your sharing.
I tried `collect-view` on Windows and it can work.
I think Linux or VM is problem perhaps.

**Comment by RaHeron95** [comment]
Hi @yoyo890121  I'm facing the same problem but using the cc2650 sensortag, could you explain to me how you could do it on windows?
