### ISSUE TITLE
Serial communication between device

### ISSUE THREAD

**Issue by MarCast** [contiki-os/contiki#2392]
Hi, I working with GW Contiki and cc1310 device node. I would like to communicate with serial via radio. For example: I write on COM3 "hi" and I read on COM5 "hi".  Can you help us?

Thanks and Regards!

**Comment by alexrayne** [comment]
try examples\rime
runicast, unicast, broadcast - examples not read anything from COM, but it prints messages, that nodes interconnects.

**Comment by MarCast** [comment]
How can I see nodes exchanging messages through the serial?

**Comment by MarCast** [comment]
@g-oikonomou

**Comment by MarCast** [comment]
Thanks @alexrayne , but how do I know the second device receives the message?

**Comment by chenek** [comment]
You can refer to the example at https://sunmaysky.blogspot.tw/2017/11/using-contiki-udp-client-to-send-onoff.html
