### ISSUE TITLE
function timer_remaining issue

### ISSUE THREAD

**Issue by ysgepl** [contiki-os/contiki#2407]
Hi,
the file core\sys\timer.c  function timer_remaining, when clock_time() is more than ( t->start + t->interval ), and the calculation is wrong,the value is always > 0.
clock_time_t
timer_remaining(struct timer *t)
{
  return t->start + t->interval - clock_time();
}

Can it be modified to be:
int diff = clock_time() -  (t->start + t->interval);
if ( diff >= 0 )
{
	return diff;
}
else
{
	return 0;
}

Thanks & Regards,

**Comment by greg-king5** [comment]
No.
- `timer_remaining()` shouldn't be called if the timer has expired.
- `diff` would need to be declared as the signed version of `clock_time_t`; but, that type isn't defined.
