### ISSUE TITLE
Updating GCC compiler to MSP430-gcc-4.7.3

### ISSUE THREAD

**Issue by Siddarth1511** [contiki-os/contiki#2464]
I am having trouble in updating msp430-gcc from version 4.7.0 to 4.7.3 as given in this link https://github.com/pksec/msp430-gcc-4.7.3

I did everything, from copying the msp430 file to opt/compilers to adding the path as given in the readme file.

It still is not updating ( i am saying this because i get error: rpl-tsch code will not fit because ram overflown by some 8K bytes)

does anyone else this issue

**Comment by basitmushtaq** [comment]
did you fix it? if so can you please tell  me how you did it?

**Comment by Siddarth1511** [comment]
> did you fix it? if so can you please tell me how you did it?

Please refer to the issue number #2280 
I used that issue to resolve my issue as well.
