### ISSUE TITLE
Which stack is efficient to use in a low power sensor network?? RPL-TSCH (in 6LowPAN) or TSCH with rime??

### ISSUE THREAD

**Issue by Siddarth1511** [contiki-os/contiki#2467]

**Comment by alexrayne** [comment]
it depends on need routing or not.
for simple net without routing - Rime prefere

**Comment by Siddarth1511** [comment]
say if we do not want routing. 
Then which do you think is most efficient ?
Since you are saying rime is preferred. on what basis it is preferred. how it is efficient and better (without routing)

**Comment by alexrayne** [comment]
> how it is efficient and better (without routing)
it just gives simpler code, requres less RAM, and not generates router traffic. that is all preferences.
if you need some like DHCP, heibohour detection - so maybe you need full ipv6 stack

**Comment by Siddarth1511** [comment]
alright thanks for your help :) 👍 
@alexrayne
