### ISSUE TITLE
Incorrect pointer's fields problem with the list

### ISSUE THREAD

**Issue by erfanlinman** [contiki-os/contiki#2510]
#Question
Hi, I using the Contiki 3, cloned from git. I add the following method to the rpl_dag.c module and use list_init() and memb_init() in dag_init() method. I call my method (__nbrShow__) in best_parent() method in the rpl_dag module. I noticed a problem with printing data; before I push the pointer __temp__ in the list all the printed fields are correct but after that in two places are field are wrong except IP address. I wonder someone gives hand to me and describe which part of my code has a problem or I don't know just describe the why and what happens in there, it gets in my nerves. And I have been using the Contiki Mote.
```c
struct rpl_nbr {
    uint8_t order;
    uint16_t rank;
    uip_ipaddr_t *ipaddr;
};
typedef struct rpl_nbr rpl_nbr_t;


void
nbrShow (){ 
  
  if(default_instance == NULL || default_instance->current_dag == NULL || rpl_parents == NULL){
    return;
  }
  
  rpl_dag_t *dag = default_instance->current_dag;
  if(dag == NULL || dag->instance == NULL || dag->instance->of == NULL) {
    return;
  }

  rpl_nbr_t *temp = memb_alloc(&nbrsmemb);
  rpl_parent_t *best = dag->preferred_parent;

  if(temp != NULL && best != NULL){
   
    temp->ipaddr = rpl_get_parent_ipaddr(best);
    temp->rank = rpl_rank_via_parent(best);
    temp->order = 0;

    PRINTF("NBR: temp %u %u ", temp->rank, temp->order);
    PRINT6ADDR(temp->ipaddr);
    PRINTF("\n");
    // all data printed before push is correct
    list_push(nbrsList, temp);
    // now just the ip address printed correctly and other structure's fields are completely wrong
    PRINTF("NBR: temp %u %u ", temp->rank, temp->order);
    PRINT6ADDR(temp->ipaddr);
    PRINTF("\n");
  }
  else{
    rpl_nbr_t *tem;
    for(tem = list_head(nbrsList); tem != NULL; tem = list_item_next(nbrsList)){
    // and here when iterating the list for freeing memory, again all printed fileds are wrong except ip address
      PRINTF("NBR: remove %u %u ", tem->rank, tem->order);
      PRINT6ADDR(tem->ipaddr);
      PRINTF("\n");
      list_remove(nbrsList, tem);
      memb_free(&nbrsmemb, tem);
    }
    PRINTF("NBR: free all\n");

  }
}
```

**Comment by nfi** [comment]
The List library in Contiki is based on a data type assumed to have a next pointer as first element. In order to use `struct rpl_nbr` as a list element, you need to add a next pointer as first element in the struct.

```
typedef struct rpl_nbr rpl_nbr_t;
struct rpl_nbr {
  rpl_nbr_t *next;
  uint8_t order;
  uint16_t rank;
  uip_ipaddr_t *ipaddr;
};
```

You can read more about the List library here: https://github.com/contiki-os/contiki/wiki/Libraries#The_List_Library
