### ISSUE TITLE
tsch:! not associated, drop outgoing packet. (only channel scanning is happening)

### ISSUE THREAD

**Issue by souhilak** [contiki-os/contiki#2585]
Hi, when i try to run rpl-tsch in contiki this problem appears 
tsch:! not associated, drop outgoing packet.
When i creat a root-node (role-6dr)and source -node (role_6ln) the simulation work fine. 
but when i try to add other source node or intermediate nodes the problem of tsch not associated appears again !!!!!
It's the same problem of @lamnd09 and  @Siddarth1511
please help me

**Comment by lamnd09** [comment]
Hi, what kind of scheduling strategy you use ? maybe you need to enable it by changing number from 0 to 1 in project-conf.h file. It will work.
/* Set to run orchestra /
#ifndef WITH_ORCHESTRA
#define WITH_ORCHESTRA 1
#endif / WITH_ORCHESTRA */

Anyway, if it does not work, could you show some screenshot of log ?

**Comment by souhilak** [comment]
Hi @lamnd09
 i enabled orchestra by changing number to 1 in project-conf.h!!

**Comment by souhilak** [comment]
@lamnd09
![TSCH1](https://user-images.githubusercontent.com/49791310/57167221-4eefc280-6dfd-11e9-815a-0afb57215ccb.PNG)
![Capture2](https://user-images.githubusercontent.com/49791310/57167241-5fa03880-6dfd-11e9-8e44-01da7496cd95.PNG)

**Comment by lamnd09** [comment]
It seems like you have not configured for the topology, which node would be root node.
