### ISSUE TITLE
RPL-TSCH

### ISSUE THREAD

**Issue by souhilak** [contiki-os/contiki#2588]
Hi @simonduq @Conrad2210 @yatch
i'm new in contiki especially in TSCH protocol,
i tested RPL-TSCH-UDP by sending a trafic, a network that is formed by a grid of 16 nodes has been defined, in which only one of them takes on the role of coordinator , one sender and 14 intermediate nodes , but with basic rpl-udp gives me better results than with tsch!!
![Capture3](https://user-images.githubusercontent.com/49791310/57201581-1ede2600-6f9b-11e9-8578-ef49e9c31bed.PNG)
![Capture2](https://user-images.githubusercontent.com/49791310/57201582-243b7080-6f9b-11e9-8fc2-440c16cd3971.PNG)
![Capturetsch](https://user-images.githubusercontent.com/49791310/57201585-2d2c4200-6f9b-11e9-8fa6-b600fa79450c.PNG)

**Comment by yatch** [comment]
Since I'm not active on contiki, I don't remember what is implemented in the example... I believe you need to learn what TSCH is, and how different TSCH is from CSMA.

>  with basic rpl-udp gives me better results than with tsch!!

Then, you will understand why you had better results in CSMA.

**Comment by souhilak** [comment]
Thenkyou @yatch
