### ISSUE TITLE
FIFO Buffer

### ISSUE THREAD

**Issue by harihary** [contiki-os/contiki#2626]
I need to implement a FIFO Buffer. How do I go about that. I can't use #include "FIFO.h" here I want to store some data from one of the sensors  about 8 to 10 in number and analyze.  Anyone has any idea?

**Comment by alexrayne** [comment]
core/lib/ringbuf.h doesn`t helps you?

**Comment by harihary** [comment]
I used array to store and complete the programming.

Regards,
Hari

**Comment by alexrayne** [comment]
so you can just close this issue?

**Comment by harihary** [comment]
Thanks
