### ISSUE TITLE
residual cleanup needed for uip routing code

### ISSUE THREAD

**Issue by pabigot** [contiki-os/contiki#268]
In afe13b22bc3c29fd80a5b58bc691f5819630c2d8 the uIP IPv6 route handling code was replaced.  As a side effect, the isused field was removed from uip_ds6_route_t and uip_ds6_defrt_t.  Some cleanup was done in 99f541e8fd30b9329e04bfc9ed9aa718dc246a3f but references to these fields remain in conditionally-compiled code in apps/webserver-nano/httpd-cgi.c (encountered reproducing #249) and per "git grep" avr-ravenusb.  There's also commented-out code that still uses it.

**Comment by alignan** [comment]
Sadly outdated
