### ISSUE TITLE
rtimer documentation doesn't match reality

### ISSUE THREAD

**Issue by karlp** [contiki-os/contiki#275]
What little documentation there is:
http://contiki.sourceforge.net/docs/2.6/a01671.html
and
https://github.com/contiki-os/contiki/wiki/Timers#wiki-The_Rtimer_Library
and the sys/rtimer.h file all imply that rtimer_set can actually return some sort of status.

however, in the source, the only possible return code is RTIMER_OK.

Is this a) a bug, or b) by design?

contikimac.c uses the function rtimer_arch_sleep(), but that's not listed in any documentaiton, and only defined for AVR and mc1322x.  Bug or design?

Is the rtimer code actually _meant_ to be used by any user processes, or is it purely designed for use by the MAC driver code?

**Comment by g-oikonomou** [comment]
Idle. Closing
