### ISSUE TITLE
Support for supporting WERROR=1?

### ISSUE THREAD

**Issue by pabigot** [contiki-os/contiki#277]
Contiki's build environment nominally supports using WERROR=1 to turn on gcc -Werror checking.  I find this feature helps reduce the number of bugs I introduce, but Contiki's source has several "errors" in core files that prevent its use.

Most of these are variables that are declared and either unused or set but never referenced.  Often the reference is in code that is present but normally excluded from compilation (e.g., debug blocks).

Some are uses of functions without a prototype in scope.  Others are violations of the edges of the C standard.  A few appear to be wrong code that happens to work in most cases.

Is there support for patches to fix these issues?  A current set of such changes can be viewed at https://github.com/pabigot/contikix/tree/features/werror.  I don't want to spend the time refactoring and submitting a pull request if it's clear the approach would be rejected.

BTW: I am aware that `-Wno-error=unused-variable` could be used to reduce the number of changes.  I don't support that approach, so if review prefers it somebody else can take over from here by cherry-picking any other changes that are judged worthwhile.

**Comment by simonduq** [comment]
Contiki is now warning-free (on most platforms) with https://github.com/contiki-os/contiki/pull/1293 and https://github.com/contiki-os/contiki/pull/1364, closing this issue!
