### ISSUE TITLE
Problems using timer_reset(): etimer expires immediately which is wrong

### ISSUE THREAD

**Issue by spachner** [contiki-os/contiki#293]
Dear Contiki developers,

I am trying to use etimer's function timer_reset() which should reset an etimer without loosing precision: 

When my etimer is reset with timer_reset() it expires immediately which is wrong and breaks my system! 

timer_reset() is implemented as:

<code>
/**
* Reset the timer with the same interval.
*
* This function resets the timer with the same interval that was
* given to the timer_set() function. The start point of the interval
* is the exact time that the timer last expired. Therefore, this
* function will cause the timer to be stable over time, unlike the
* timer_restart() function.
*
* \param t A pointer to the timer.
*
* \sa timer_restart()
*/
void
timer_reset(struct timer *t)
{
 t->start += t->interval;
}
</code>

As you can see timer_reset() actually postpones the t->start into a future's value compared to current time returned by clock_time().
The etimer_process checks timer_expired() which immediately returns true (which is wrong).

<code>
int
timer_expired(struct timer *t)
{
 /* Note: Can not return diff >= t->interval so we add 1 to diff and return
    t->interval < diff - required to avoid an internal error in mspgcc. */
 clock_time_t diff = (clock_time() - t->start) + 1;
 return t->interval < diff;

}

</code>
Note that clock_time_t is defined like this (an unsigned type!)
<code>

typedef unsigned int clock_time_t;
</code>

Variable "diff = clock_time() - t->start"  cannot result in a negative value instead it is treated as a high positive value which then compared with t->interval is always true.

What is wrong? Is probably an implementation of these functions buggy?

Thanks for any advice.

spachner

**Comment by g-oikonomou** [comment]
#767

**Comment by NoNine** [comment]
I met this issue too. In some race condition(very hard to reproduce), timer_reset() is called before timer expired.

The timer_expired()'s current behavior is strange,.
Why it was designed to this way?
Is there some special purpose?

Maybe update the logic of timer_expired() can make the code more robust.

#define CLOCK_LT(a, b) (((a) - (b)) > ((~(clock_time_t)0) >> 1))
int
timer_expired(struct timer *t)
{
return CLOCK_LT(t->start + t->interval, clock_time() + 1);
}
