### ISSUE TITLE
Add Crypto / Security support

### ISSUE THREAD

**Issue by g-oikonomou** [contiki-os/contiki#526]
As discussed here:
http://sourceforge.net/mailarchive/message.php?msg_id=31642373

*Encryption and security was always missing in Contiki. At Thingsquare, we
have successfully been using AES encryption in the netstack with great
success, and we're starting to see patches coming in that take advantage of
hardware-accelerated AES encryption on devices such as the CC2538. Time to
include all this in the mainline Contiki.*

**Comment by bthebaudeau** [comment]
Can we now consider this one as closed thanks to the latest additions (#1435, #1443), or are there still a few things missing? (@kkrentz) It is supposed to be ready on CC2538, but perhaps some of the pending llsec PRs (#880, #1383, #1425) would be required for a release, or maybe we want to support this on other platforms too.

**Comment by alignan** [comment]
I think this is pretty closed now
