### ISSUE TITLE
avr-zigbit: Bad functions: rime_init() - uip_router_register()

### ISSUE THREAD

**Issue by patoman007** [contiki-os/contiki#580]
In <b><i>platform/avr-zigbit/contiki-avr-zigbit-main.c<i/></b> file, the  <i><b>rime_init(rime_udp_init(NULL));</i></b> function is wrong <i>[Line 162]</i>. The definition is <i><b>in /core/net/rime/rime.h</i></b> file: <i>rime_init(void)</i>

Also the <i><b>rimeroute</i></b> parameter is undeclared. <i>[Line 163]</i>

**Comment by g-oikonomou** [comment]
#950
