### ISSUE TITLE
Linking standart math library for CC2538

### ISSUE THREAD

**Issue by ademirci** [contiki-os/contiki#705]
I was trying to use basic math functions, sqrt, tan, atan ...
I got linker errors "undefined reference to `sqrt'" and e.t.c
I modified Makefile.cc2538 line 79 by adding "-lm" to the end of line and successfully built my code.
Could you please automate this so that people can link standart C librariries which gcc does not link by default.

**Comment by g-oikonomou** [comment]
I've thought about this for a while: The math library is not required by the port itself. 

Linking the math library has been discussed repeatedly in the mailing list, so users who actually do need it should be able to find out how to add it very easily.
