### ISSUE TITLE
Border routers break severely if there are more than one running

### ISSUE THREAD

**Issue by malvira** [contiki-os/contiki#71]
The original problem reported isn't a bug any where but is still a problem. If two border-routers are within range, the can add each other as the default route which causes the fallback interface to fail. 

---------------------
border-router_econotag.bin is not functional somewhere after pull #45. Bisecting the issue has not been useful as it seems the intermediate commits might be flaky (perhaps the problem depends on how things start up?). The current master, #69 fails all the time.

To reproduce: run a border-router and try to ping it. It will fail. 

Debug output from bad 56ce924:

'''
IPv6 packet received from aaaa::1 to aaaa::205:c2a:8c9e:4f20
icmp6_input: length 104 type: 128
Upper layer checksum len: 64 from: 40
Received Echo Request from aaaa:0000:0000:0000:0000:0000:0000:0001 to
aaaa:0000:0000:0000:0205:0c2a:8c9e:4f20
Upper layer checksum len: 64 from: 40
Sending Echo Reply to aaaa:0000:0000:0000:0000:0000:0000:0001 from
aaaa:0000:0000:0000:0205:0c2a:8c9e:4f20
Sending packet with length 104 (64)
sicslowpan output: sending packet len 104
before compression (64):
6000000000403a40aaaa00000000000002050c2a8c9e4f20aaaa00000000000000000000000000018100be303f4e01d5c8b9e95000000000c80f070000000000101112131415161718191a1b1c1d1\
e1f202122232425262728292a2b2c2d2e2f3031323334353637
IPHC: compressing dest or src ipaddr - setting CID
IPHC: compressing src with context - setting CID & SAC ctx: 0
'''

Debug output from good 0cb4bf4:

'''
IPv6 packet received from aaaa::1 to aaaa::205:c2a:8c9e:4f20
icmp6_input: length 104 type: 128 
Upper layer checksum len: 64 from: 40
Received Echo Request from aaaa:0000:0000:0000:0000:0000:0000:0001 to aaaa:0000:0000:0000:0205:0c2a:8c9e:4f20 
Upper layer checksum len: 64 from: 40
Sending Echo Reply to aaaa:0000:0000:0000:0000:0000:0000:0001 from aaaa:0000:0000:0000:0205:0c2a:8c9e:4f20 
Sending packet with length 104 (64)
Packet from SLIP of length 104 - write TUN
'''

To me, this looks like for some reason the bad code send the ping reply out sicslowpan instead of using the fallback interface which will send the ping out SLIP.

Ping isn't the only thing to fail but so does going to the BR webpage.

**Comment by joakimeriksson** [comment]
Is this problem still valid?

**Comment by laurentderu** [comment]
There has been a handful of PR about the multi dodag support and there is now a non regression test performed so I can safely say it's solved.

**Comment by Ashokrlz** [comment]
How can I simply ignore a DIO from a specific DODAG ID/IP?

**Comment by Ashokrlz** [comment]
I hope that someone can help me out here, I've created a single hop 6lowpan network with few nodes(in LEAF mode) and two 6LBR with the same Instance ID. And now I would like to force all the nodes to join a preferred border router and discard the DIOs from the other router. I was searching for some way to hardcode the preferred DODAG ID in the node's configurations file but found only RPL_DEFAULT_INSTANCE .
And for Single hop network which communication stack is recommended to use in Contiki?

Regards,
Ashok

**Comment by Ashokrlz** [comment]
![error](https://user-images.githubusercontent.com/26306475/29123724-638c48e2-7d1f-11e7-93c1-7d8af7cd5dd0.png)
Ping fails continuously when two border routers with same instance id are within range.
