### ISSUE TITLE
NETSTACK_ENCRYPT(); NETSTACK_DECRYPT();  BUG

### ISSUE THREAD

**Issue by xmxueping** [contiki-os/contiki#773]
core/net/mac/nullrdc.c use macro NETSTACK_ENCRYPT & NETSTACK_DECRYPT to encrypt and decrypt data. Encrypt process i think ok, but decrypt process does not work properly.
 I use cc2530DK, in function main(void) of /platform/cc2530dk/contiki-main.c:

    len = NETSTACK_RADIO.pending_packet();
    if(len) {
      packetbuf_clear();
      len = NETSTACK_RADIO.read(packetbuf_dataptr(), PACKETBUF_SIZE);
      if(len > 0) {
        packetbuf_set_datalen(len);
        NETSTACK_RDC.input();
      }

the all radio data put into packetbuf_dataptr(),include header of 802.15.4 layer.

In function packet_input(void) of /core/net/mac/nullrdc.c
  original_datalen = packetbuf_datalen();
  original_dataptr = packetbuf_dataptr();
#ifdef NETSTACK_DECRYPT
    NETSTACK_DECRYPT();
#endif /* NETSTACK_DECRYPT */

we commonly decrypt full data in packetbuf_dataptr() & packetbuf_datalen(),
but header of 802.15.4 layer still in the buffer.

Move decrypt process just before NETSTACK_MAC.input()? like this:

    if(!duplicate) {
      NETSTACK_MAC.input();
    }

==>

    if(!duplicate) {
#ifdef NETSTACK_DECRYPT
    NETSTACK_DECRYPT();
#endif /* NETSTACK_DECRYPT */
      NETSTACK_MAC.input();
    }

**Comment by g-oikonomou** [comment]
Merging LLSEC obsoletes this
