### ISSUE TITLE
Unknown error: javax.swing.plaf.BorderUIResource cannot be cast to java.awt.Font

### ISSUE THREAD

**Issue by ejoerns** [contiki-os/contiki#819]
This error appears from time to time when working with Cooja and also seems to be a good candidate for randomly crashing Travis tests (e.g. [1], although I'm not sure how much UI is there..).

This seems to be an error with the un-thread-safety of Nimbus and updating UI components form non-UI threads. Did not have time to put more effort into this one but it should be mentioned to not be forgotten. ;)

[1] https://travis-ci.org/contiki-os/contiki/jobs/37429165

**Comment by simonduq** [comment]
closed by https://github.com/contiki-os/contiki/pull/1987
