### ISSUE TITLE
Control Cooja with a plugin

### ISSUE THREAD

**Issue by TheGeorge** [contiki-os/contiki#840]
Currently it is not possible to control Cooja with a plugin that has no GUI unless it's a ScriptRunner.

If cooja is run in nogui mode, it is required that a ScriptRunner plugin is loaded, otherwise Cooja will quit immediately.

This behaviour is hardcoded in Cooja.java line 3250:

```
/* Make sure at least one test editor is controlling the simulation */
boolean hasEditor = false;
for (Plugin startedPlugin : gui.startedPlugins) {
  if (startedPlugin instanceof ScriptRunner) {
    hasEditor = true;
    break;
}
...
```

It would be nice if we could write our own control plugins, or disable the requirement for a ScriptRunner plugin in nogui mode completely.

**Comment by azeemjahangir** [comment]
my scrip is not working of PDR and latency whats the running process please let me know step by step.
I  copied and paced in sim script but result cannot get .the examples are working but pdr and latency code is not working ..
