### ISSUE TITLE
linker script for cc2538 doesn't align sections

### ISSUE THREAD

**Issue by bagel99** [contiki-os/contiki#854]
This causes data copy and bss clearing to use unaligned access.
Patch:
--- a/cpu/cc2538/cc2538.lds
+++ b/cpu/cc2538/cc2538.lds
@@ -77,6 +77,7 @@ SECTIONS
         KEEP(*(.vectors))
         *(.text*)
         *(.rodata*)
+        . = ALIGN (4);
         _etext = .;
     } > FLASH= 0
 
@@ -89,6 +90,7 @@ SECTIONS
     {
         _data = .;
         *(.data*)
+        . = ALIGN (4);
         _edata = .;
     } > SRAM AT > FLASH
 
@@ -102,6 +104,7 @@ SECTIONS
         _bss = .;
         *(.bss*)
         *(COMMON)
+        . = ALIGN (4);
         _ebss = .;
     } > SRAM

**Comment by ThreadedThinking** [comment]
I have been getting the error "ERROR: Invalid data size: xxxxxx. Size must be a multiple of 4."  I have tried this fix it does not help.  I am not very well versed in the linking process but if you need any environmental information, just let me know.

**Comment by g-oikonomou** [comment]
#1075
