### ISSUE TITLE
random for cc2538 alway generates even number

### ISSUE THREAD

**Issue by bagel99** [contiki-os/contiki#855]
Patch:
--- a/cpu/cc2538/dev/random.c
+++ b/cpu/cc2538/dev/random.c
@@ -117,8 +117,8 @@ random_init(unsigned short seed)
    */
   while(s == 0x0000 || s == 0x8003) {
     for(i = 0; i < 16; i++) {
-      s |= (REG(RFCORE_XREG_RFRND) & RFCORE_XREG_RFRND_IRND);
       s <<= 1;
+      s |= (REG(RFCORE_XREG_RFRND) & RFCORE_XREG_RFRND_IRND);
     }
   }

**Comment by g-oikonomou** [comment]
Cannot reproduce this. I am getting odds as well as evens
