### ISSUE TITLE
CC2538 rpl-udp nodes crash occasionally

### ISSUE THREAD

**Issue by dazhbog** [contiki-os/contiki#870]
Hi,
Ive been working with contiki for a while now and I've been having this issue where nodes seem to occasionally crash. The watchdog doesn't seem to kick in, they just hang and all the peripherals stop. The example I use is the rpl-udp (1 server and a couple of clients). I use the vanilla contiki repo. I also use a modified version that reads i2c, etc. and that also has the same issue. At first I thought that maybe there is max reattempt count that is reached. But it seems that when it crashes, I2C and blinking (separate processes) also stop working, 

My hardware is the CC2538EM Texas Instruments dev board.

Startup sequence:
> Net: sicslowpan
> MAC: CSMA
> RDC: ContikiMAC
> Rime configured with address 00:12:4b:00:04:0e:f3:83
> UDP client process started
> Client IPv6 addresses: aaaa::212:4b00:40e:f383
> fe80::212:4b00:40e:f383
> Created a connection with the server :: local/remote port 8765/5678

Any ideas? Am I missing something?

**Comment by mcr** [comment]
Does it happen with different instances of the CC2538EM hardware?  
Do you have any console available?  I guess you power cycle it, and it is sane again?

**Comment by dazhbog** [comment]
So I did some more testing with a more stable power supply. My new PCBs arrived and those have a fuel gauge and an external watchdog and some other cool stuff. That means that I can monitor more what goes on. For example, every time a node restarts, its packet counter gets reset so I get this graph on my server (see attached). 

I need to be able to distinguish a hardware reset from a watchdog reset (I've seen it somewhere in the code, anyone used it?). This way I will know when contiki resets it self vs completely crashing and getting saved by the external watchdog. That should give a better view on the problem, maybe there is some periodicity in the resets, or build X vs build Y causes more crashes.

Also with the new battery node it hasn't crashed for days now, so It might have been a power supply issue. I will keep testing.

Do you guys use the current git version as the stable version or do you use the 2.7 release branch?

![2015-01-11 15 13 33](https://cloud.githubusercontent.com/assets/1836262/5696223/0fe13f0a-99a5-11e4-8b3d-f988630c8728.jpg)
![screenshot 2015-01-11 15 18 55](https://cloud.githubusercontent.com/assets/1836262/5696225/376ffd0e-99a5-11e4-98bb-2691551e99ce.png)

**Comment by g-oikonomou** [comment]
> I need to be able to distinguish a hardware reset from a watchdog reset (I've seen it somewhere in the code, anyone used it?).

Could bits `RST` of the `SYS_CTRL_CLOCK_STA` be what you're looking for?

I personally always try using latest version from git than releases.

**Comment by dazhbog** [comment]
@g-oikonomou Thanks for the hint.

It seems that the issue was power as there was no restart for many days. Closing for now :-)
