### ISSUE TITLE
CC2538 - GPIO Power-up interrupt doesn't execute the callback function

### ISSUE THREAD

**Issue by darkopetrovic** [contiki-os/contiki#921]
I've disabled ContikiMAC with `NETSTACK_RDC.off(0)`. Then there is no more automatic wake-up from the SM Timer. I've a button connected to a pin on the port D to wake-up the SoC when it is pressed. I added in the configuration of button:

```cpp
GPIO_POWER_UP_ON_FALLING(BUTTON_USER_PORT, BUTTON_USER_PIN_MASK);
GPIO_ENABLE_POWER_UP_INTERRUPT(BUTTON_USER_PORT, BUTTON_USER_PIN_MASK);
``` 
The SoC now wakes-up correctly from LPM2. 

But when the ISR of the port `gpio_port_d_isr` is triggered, this latter doesn't execute the callback function associated with the pin because the GPIO_MIS register is not updated at this time (since the source of the interrupt is coming from the power-up interrupt and not from the general interrupt: they are separated). 

Then in order that this interrupt handler can see the source of the interrupt is coming from the power-up interrupt, we need to look at the GPIO_IRQ_DETECT_ACK register too, thus I replaced:

```
notify(REG(GPIO_D_BASE | GPIO_MIS), GPIO_D_NUM);
```

by 

```
notify(REG(GPIO_D_BASE | GPIO_MIS) | REG(GPIO_D_BASE | GPIO_IRQ_DETECT_ACK)>>24 , GPIO_D_NUM);
```

There is no such problem when the RDC is activated because the SoC wakes-up continuously and can see the general interrupt the next time it wakes-up. 

I know that it's not in the philosophy of Contiki to disable the RDC but in the case one would save power from the battery, we should be able to deactivate the RDC when it is not needed and reactivate it for example by pressing an external button. Therefore, in order to do that properly, we need to check equally the `GPIO_IRQ_DETECT_ACK` register in the GPIO interrupt handler.  

Reference: http://e2e.ti.com/support/wireless_connectivity/f/158/p/320838/1376612

**Comment by g-oikonomou** [comment]
This should be fixed now (#1031)
