### ISSUE TITLE
examples/hello-world does not compile/run for target c64

### ISSUE THREAD

**Issue by marcas756** [contiki-os/contiki#930]
The hello world example does not compile. The problem seems to be caused by the current work on IPv6 .

Regression tests do not cover the hello world example, thus travis does not complain about this issue.
I tried to compile the webserver and mail example (also done by travis)... both get compiled for taget c64 

I think that it would be a good idea to add  hello-world to regression test for all platforms, as
this example is the starting point for most people. I think it should work out of the box if the build/bin tools are correctly installed.

 make TARGET=c64
  CC        ../../cpu/6502/net/ethernet-drv.c
../../cpu/6502/net/ethernet-drv.c(64): Error: Undefined symbol: `IPBUF'
../../cpu/6502/net/ethernet-drv.c(64): Error: Struct pointer expected
../../cpu/6502/net/ethernet-drv.c(64): Error: Struct/union has no field named `srcipaddr'
../../cpu/6502/net/ethernet-drv.c(64): Error: Illegal address
../../cpu/6502/net/ethernet-drv.c(64): Error: Incompatible pointer types
../../cpu/6502/net/ethernet-drv.c(91): Error: Incompatible pointer types
make: *** [obj_c64/ethernet-drv.o] Fehler 1

see #931
cc65 issue?

**Comment by marcas756** [comment]
Hello,

i was only able to get hello-world up and running with modifying Makefile (IPV4 = 1) and 6502 main loop. 

In the main loop I removed all network stuff to get it up and running. But I did not check it in as I am afraid to break something else with this.

The same I had to do for following pull request to work on 6502 (also did not check the mentioned changes in) :  #934

I am working with the current cc65 main branch.

Regards marcas

**Comment by marcas756** [comment]
Hello,

in the meantime I got one issue solved. 

VICE complained that it could not open a file:

Fsdrive: error - cannot open file. status $02

As ethernet requires a disk image to load "contiki.cfg" I built contiki with 

export C1541=c1541
make disk TARGET=c64

and setting

CONTIKI_WITH_IPV4 = 1

in the hello-world example Makefile.

But with the same result, No "Hello world!"

```
load"$",8

searching for $
loading
ready.
list

0 "contiki         " 00 2a
68   "contiki"          prg
1    "contiki.cfg"      seq
3    "cs8900a.eth"      seq
3    "lan91c96.eth"     seq
589 blocks free.
ready.
load"*",8,1

searching for *
loading
ready.
run

ready.
```

A proposal from my side would be to add a network enable/diasable switch
```C
 #if WITH_NWK ... 
```
to contiki-main.c of c64 platform, to be able to switch network support on and off for examples by adding/removing it to Makefile.c64.defines of the examples.

Any feedback welcome

Regards marcas

**Comment by oliverschmidt** [comment]
Hi,

> As ethernet requires a disk image to load "contiki.cfg" I built contiki
> with
>
> export C1541=c1541
> make disk TARGET=c64
>
Yep, that's how it's supposed to be done.

> and setting
>
> CONTIKI_WITH_IPV4 = 1
>
Yep, as already discussed this is necessary since IPv6 was made the default
- and there's no per-target override option.

> But with the same result, No "Hello world!"
>
Maybe you just don't have have the Ethernet emulation enabled in VICE? You
want to emulate an "RR-Net". The network drivers are always loaded. And if
the Ethernet hardware detection fails the program exits.

Regards,
Oliver

**Comment by marcas756** [comment]
Hello,

thank you for the hint.

Followed the instructions on 

http://www.lyonlabs.org/commodore/building-vice-on-ubuntu.html

And after some effort and vice support I now get following result:

![image](https://cloud.githubusercontent.com/assets/8344035/6237072/098d03ba-b6f0-11e4-86e3-33247c7e8fb0.png)

Regards marcas

**Comment by oliverschmidt** [comment]
Hi,

> [image: image]
> <https://cloud.githubusercontent.com/assets/8344035/6237072/098d03ba-b6f0-11e4-86e3-33247c7e8fb0.png>
>
Yep. That's exactly the expected result !

Pretty straight forward to get there - wasn't it? ;-))

Regards,
Oliver
