### ISSUE TITLE
Code / Comment conflict for UIP_CONF_IPV6

### ISSUE THREAD

**Issue by skaterdude** [contiki-os/contiki#935]
The code at line 78 in uip.c does not match the comment that goes with it.  The compiler directive simply checks if the parameter UIP_CONF_IPV6 is true or false.  The comment, however, says that it is determining if the parameter is defined or not.  Since I do not yet have a working version of the code, I cannot check if this works by accident in some cases and doesn't in others, or if this is an acceptable way of describing the code.  To a noob like me, this looks wrong.

**Comment by darkopetrovic** [comment]
By default UIP_CONF_IPV6 is set to 0 if it is not defined. The comment refer to the default behavior configured in contiki-default-conf.h.

As a coding standard, in contiki-os, each parameters are set to a default value if they are not defined.
