### ISSUE TITLE
uip6: Wrong pseudo header for upper layer checksum calculation? 

### ISSUE THREAD

**Issue by OlegHahm** [contiki-os/contiki#940]
Looking at the IPv6 upper layer checksum calculation in https://github.com/contiki-os/contiki/blob/master/core/net/ipv6/uip6.c#L353, it seems that the pseudo header construction is not compliant with [RFC 2460, 8.1](https://tools.ietf.org/html/rfc2460#section-8.1). Instead of using the destination **and** the source address, the latter one is used twice. Am I missing something or is this a bug?

**Comment by adamdunkels** [comment]
The destination address is located directly after the source address in memory. The code isn't very obvious about this.

**Comment by OlegHahm** [comment]
Ah, thanks, should have looked more thoroughly.
