### ISSUE TITLE
Driver for the SmartRF06EB LCD

### ISSUE THREAD

**Issue by latapata** [contiki-os/contiki#943]
Hello All,

I need Driver for the SmartRF06EB LCD so that i can debug programs easily. Has anyboody an Idea. I am also in the process of developing it in case it is readily available I will use it.

**Comment by darkopetrovic** [comment]
Please don't post messages that are not directly related to contiki. Thank you.

**Comment by latapata** [comment]
Hello,
I thought this was a valid question. Because using contiki I want to work with the LCD of smartRF06EB. I have implemented codes of TI along with the the contiki programs but becuase of the difference in header files the display is not functioning
