### ISSUE TITLE
File overwrite? Intended behavior? 

### ISSUE THREAD

**Issue by mkschreder** [contiki-os/contiki#955]
When I tried opening an existing coffee fs file and writing to it, I had flash data being written to the same location (obviously resulting in garbage). Why is coffee fs not writing a new page when trying to overwrite an existing file? Do I always have to delete a file first when I need to overwrite it?

**Comment by nvt** [comment]
It depends on the platform's configuration; Coffee should not overwrite flash data if COFFEE_MICRO_LOGS is set to 1 in cfs-coffee-arch.h.

**Comment by mkschreder** [comment]
Ok that worked. Should be the default. It was very surprising to see file data corrupted when opening an existing file for writing..

**Comment by nvt** [comment]
The default in Coffee is that COFFEE_MICRO_LOGS is 1. Among current Contiki platforms, avr-raven and native are the ones that set it to 0.
