### ISSUE TITLE
er-rest-example on SmartRF06 board

### ISSUE THREAD

**Issue by serafimdasaudade** [contiki-os/contiki#975]
Hi, 
Today I did git clone from the master branch, and try the er-example-server.
And the example didn't work. But is I run the same example, from the branch Contikie-2.7 runs OK.
But the output is strange:
Contiki-2.6-2048-g0c7d261
TI SmartRF06 + cc2538EM
 Net: sicslowpan
 MAC: nullmac
 RDC: nullrdc
Rime configured with address 00:12:4b:00:04:13:32:6d

Why is Contiki-2.6 version.
Did I make the compilation wrong?

tks,

**Comment by g-oikonomou** [comment]
I can see nothing wrong with the Contiki version string.

I am not sure what you mean by "the example didn't work". What's your setup? What behaviour did you expect? What did you observe?

**Comment by g-oikonomou** [comment]
Inactive. Closing
